package com.hha.types

/**
 * Represents the different shapes a table can have on the floor plan.
 */
enum class EShape
{
   SHAPE_SQUARE,
   SHAPE_CIRCULAR,
   SHAPE_PERSON_AVATAR01,
   SHAPE_PERSON_AVATAR02,
   SHAPE_PERSON_AVATAR03,
   SHAPE_PERSON_AVATAR04,
   SHAPE_PERSON_AVATAR05,
   SHAPE_PERSON_AVATAR06,
   SHAPE_PERSON_AVATAR07,
   SHAPE_PERSON_AVATAR08,
   SHAPE_PERSON_AVATAR09,
   SHAPE_PERSON_AVATAR10,
   SHAPE_PERSON_AVATAR11,
   SHAPE_PERSON_AVATAR12,
   SHAPE_PERSON_RESERVATION
}
