# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_types_pb2 as common__types__pb2
import sql_prepare_transaction_pb2 as sql__prepare__transaction__pb2


class PrepareTransactionServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.UpdatePrepareTransaction = channel.unary_unary(
        '/pt.PrepareTransactionService/UpdatePrepareTransaction',
        request_serializer=sql__prepare__transaction__pb2.PrepareTransaction.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.RemoveFinishedTransactions = channel.unary_unary(
        '/pt.PrepareTransactionService/RemoveFinishedTransactions',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.GetTransactionMap = channel.unary_unary(
        '/pt.PrepareTransactionService/GetTransactionMap',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=sql__prepare__transaction__pb2.PrepareTransactionMap.FromString,
        )
    self.GetAllVisibleTransactions = channel.unary_unary(
        '/pt.PrepareTransactionService/GetAllVisibleTransactions',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=sql__prepare__transaction__pb2.PrepareTransactionList.FromString,
        )
    self.GetAllNewTransactions = channel.unary_unary(
        '/pt.PrepareTransactionService/GetAllNewTransactions',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=sql__prepare__transaction__pb2.PrepareTransactionList.FromString,
        )
    self.SetState = channel.unary_unary(
        '/pt.PrepareTransactionService/SetState',
        request_serializer=sql__prepare__transaction__pb2.SetStateRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.Clear = channel.unary_unary(
        '/pt.PrepareTransactionService/Clear',
        request_serializer=sql__prepare__transaction__pb2.ClearRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.AddPrepare = channel.unary_unary(
        '/pt.PrepareTransactionService/AddPrepare',
        request_serializer=sql__prepare__transaction__pb2.AddPrepareRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )


class PrepareTransactionServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def UpdatePrepareTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveFinishedTransactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransactionMap(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllVisibleTransactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllNewTransactions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Clear(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddPrepare(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PrepareTransactionServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'UpdatePrepareTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.UpdatePrepareTransaction,
          request_deserializer=sql__prepare__transaction__pb2.PrepareTransaction.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'RemoveFinishedTransactions': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveFinishedTransactions,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'GetTransactionMap': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransactionMap,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=sql__prepare__transaction__pb2.PrepareTransactionMap.SerializeToString,
      ),
      'GetAllVisibleTransactions': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllVisibleTransactions,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=sql__prepare__transaction__pb2.PrepareTransactionList.SerializeToString,
      ),
      'GetAllNewTransactions': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllNewTransactions,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=sql__prepare__transaction__pb2.PrepareTransactionList.SerializeToString,
      ),
      'SetState': grpc.unary_unary_rpc_method_handler(
          servicer.SetState,
          request_deserializer=sql__prepare__transaction__pb2.SetStateRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'Clear': grpc.unary_unary_rpc_method_handler(
          servicer.Clear,
          request_deserializer=sql__prepare__transaction__pb2.ClearRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'AddPrepare': grpc.unary_unary_rpc_method_handler(
          servicer.AddPrepare,
          request_deserializer=sql__prepare__transaction__pb2.AddPrepareRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pt.PrepareTransactionService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
