# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_types_pb2 as common__types__pb2
import sql_daily_transaction_print_pb2 as sql__daily__transaction__print__pb2


class DailyTransactionPrintServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.FindPrintTimeFrame = channel.unary_unary(
        '/dtp.DailyTransactionPrintService/FindPrintTimeFrame',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=sql__daily__transaction__print__pb2.TimeFrame.FromString,
        )
    self.PrintTimeFrame = channel.unary_unary(
        '/dtp.DailyTransactionPrintService/PrintTimeFrame',
        request_serializer=sql__daily__transaction__print__pb2.PrintTimeFrameRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.Verify = channel.unary_unary(
        '/dtp.DailyTransactionPrintService/Verify',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=sql__daily__transaction__print__pb2.VerifyResponse.FromString,
        )
    self.SetPrinted = channel.unary_unary(
        '/dtp.DailyTransactionPrintService/SetPrinted',
        request_serializer=sql__daily__transaction__print__pb2.SetPrintedRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )


class DailyTransactionPrintServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def FindPrintTimeFrame(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PrintTimeFrame(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Verify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetPrinted(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DailyTransactionPrintServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'FindPrintTimeFrame': grpc.unary_unary_rpc_method_handler(
          servicer.FindPrintTimeFrame,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=sql__daily__transaction__print__pb2.TimeFrame.SerializeToString,
      ),
      'PrintTimeFrame': grpc.unary_unary_rpc_method_handler(
          servicer.PrintTimeFrame,
          request_deserializer=sql__daily__transaction__print__pb2.PrintTimeFrameRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'Verify': grpc.unary_unary_rpc_method_handler(
          servicer.Verify,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=sql__daily__transaction__print__pb2.VerifyResponse.SerializeToString,
      ),
      'SetPrinted': grpc.unary_unary_rpc_method_handler(
          servicer.SetPrinted,
          request_deserializer=sql__daily__transaction__print__pb2.SetPrintedRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dtp.DailyTransactionPrintService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
