# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sql_archive_menu_name.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_types_pb2 as common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sql_archive_menu_name.proto',
  package='amn',
  syntax='proto3',
  serialized_pb=_b('\n\x1bsql_archive_menu_name.proto\x12\x03\x61mn\x1a\x12\x63ommon_types.proto\"\"\n\nMenuItemId\x12\x14\n\x0cmenu_item_id\x18\x01 \x01(\x05\"\x1d\n\x0cSqlStatement\x12\r\n\x05query\x18\x01 \x01(\t\"-\n\x0bNameRequest\x12\r\n\x05local\x18\x01 \x01(\t\x12\x0f\n\x07\x63hinese\x18\x02 \x01(\t2\xc6\x01\n\x16\x41rchiveMenuNameService\x12;\n\x19\x41\x64\x64NamesFromCurrentOrders\x12\r.common.Empty\x1a\r.common.Empty\"\x00\x12\x33\n\x0b\x43onvertName\x12\x0f.amn.MenuItemId\x1a\x11.amn.SqlStatement\"\x00\x12:\n\x13\x46indArchiveMenuName\x12\x10.amn.NameRequest\x1a\x0f.amn.MenuItemId\"\x00\x42+\n\x19\x63om.hha.archive.menu.nameP\x01\xaa\x02\x0bGrpcServiceb\x06proto3')
  ,
  dependencies=[common__types__pb2.DESCRIPTOR,])




_MENUITEMID = _descriptor.Descriptor(
  name='MenuItemId',
  full_name='amn.MenuItemId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='menu_item_id', full_name='amn.MenuItemId.menu_item_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=90,
)


_SQLSTATEMENT = _descriptor.Descriptor(
  name='SqlStatement',
  full_name='amn.SqlStatement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='amn.SqlStatement.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=121,
)


_NAMEREQUEST = _descriptor.Descriptor(
  name='NameRequest',
  full_name='amn.NameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='local', full_name='amn.NameRequest.local', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chinese', full_name='amn.NameRequest.chinese', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=168,
)

DESCRIPTOR.message_types_by_name['MenuItemId'] = _MENUITEMID
DESCRIPTOR.message_types_by_name['SqlStatement'] = _SQLSTATEMENT
DESCRIPTOR.message_types_by_name['NameRequest'] = _NAMEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MenuItemId = _reflection.GeneratedProtocolMessageType('MenuItemId', (_message.Message,), dict(
  DESCRIPTOR = _MENUITEMID,
  __module__ = 'sql_archive_menu_name_pb2'
  # @@protoc_insertion_point(class_scope:amn.MenuItemId)
  ))
_sym_db.RegisterMessage(MenuItemId)

SqlStatement = _reflection.GeneratedProtocolMessageType('SqlStatement', (_message.Message,), dict(
  DESCRIPTOR = _SQLSTATEMENT,
  __module__ = 'sql_archive_menu_name_pb2'
  # @@protoc_insertion_point(class_scope:amn.SqlStatement)
  ))
_sym_db.RegisterMessage(SqlStatement)

NameRequest = _reflection.GeneratedProtocolMessageType('NameRequest', (_message.Message,), dict(
  DESCRIPTOR = _NAMEREQUEST,
  __module__ = 'sql_archive_menu_name_pb2'
  # @@protoc_insertion_point(class_scope:amn.NameRequest)
  ))
_sym_db.RegisterMessage(NameRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031com.hha.archive.menu.nameP\001\252\002\013GrpcService'))

_ARCHIVEMENUNAMESERVICE = _descriptor.ServiceDescriptor(
  name='ArchiveMenuNameService',
  full_name='amn.ArchiveMenuNameService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=171,
  serialized_end=369,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddNamesFromCurrentOrders',
    full_name='amn.ArchiveMenuNameService.AddNamesFromCurrentOrders',
    index=0,
    containing_service=None,
    input_type=common__types__pb2._EMPTY,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ConvertName',
    full_name='amn.ArchiveMenuNameService.ConvertName',
    index=1,
    containing_service=None,
    input_type=_MENUITEMID,
    output_type=_SQLSTATEMENT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindArchiveMenuName',
    full_name='amn.ArchiveMenuNameService.FindArchiveMenuName',
    index=2,
    containing_service=None,
    input_type=_NAMEREQUEST,
    output_type=_MENUITEMID,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARCHIVEMENUNAMESERVICE)

DESCRIPTOR.services_by_name['ArchiveMenuNameService'] = _ARCHIVEMENUNAMESERVICE

# @@protoc_insertion_point(module_scope)
