# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sql_tax_cluster.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_types_pb2 as common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sql_tax_cluster.proto',
  package='taxcl',
  syntax='proto3',
  serialized_pb=_b('\n\x15sql_tax_cluster.proto\x12\x05taxcl\x1a\x12\x63ommon_types.proto\"&\n\x0cTaxClusterId\x12\x16\n\x0etax_cluster_id\x18\x01 \x01(\x05\"s\n\nTaxCluster\x12\x16\n\x0etax_cluster_id\x18\x01 \x01(\x05\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x14\n\x0cmenu_card_id\x18\x03 \x01(\x05\x12\x12\n\nlocal_name\x18\x04 \x01(\t\x12\x14\n\x0c\x63hinese_name\x18\x05 \x01(\t\"8\n\x0eTaxClusterList\x12&\n\x0btax_cluster\x18\x01 \x03(\x0b\x32\x11.taxcl.TaxCluster2\xeb\x03\n\x11TaxClusterService\x12\x38\n\x0eGetTaxClusters\x12\r.common.Empty\x1a\x15.taxcl.TaxClusterList\"\x00\x12\x37\n\x0f\x45raseTaxCluster\x12\x13.taxcl.TaxClusterId\x1a\r.common.Empty\"\x00\x12\x36\n\x10UpdateTaxCluster\x12\x11.taxcl.TaxCluster\x1a\r.common.Empty\"\x00\x12\x41\n\x13\x44uplicateTaxCluster\x12\x13.taxcl.TaxClusterId\x1a\x13.taxcl.TaxClusterId\"\x00\x12\x38\n\x10LowestTaxCluster\x12\r.common.Empty\x1a\x13.taxcl.TaxClusterId\"\x00\x12\x39\n\x11HighestTaxCluster\x12\r.common.Empty\x1a\x13.taxcl.TaxClusterId\"\x00\x12\x39\n\rGetTaxCluster\x12\x13.taxcl.TaxClusterId\x1a\x11.taxcl.TaxCluster\"\x00\x12\x38\n\x10InsertTaxCluster\x12\r.common.Empty\x1a\x13.taxcl.TaxClusterId\"\x00\x42\x17\n\x13\x63om.hha.tax.clusterP\x01\x62\x06proto3')
  ,
  dependencies=[common__types__pb2.DESCRIPTOR,])




_TAXCLUSTERID = _descriptor.Descriptor(
  name='TaxClusterId',
  full_name='taxcl.TaxClusterId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tax_cluster_id', full_name='taxcl.TaxClusterId.tax_cluster_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=90,
)


_TAXCLUSTER = _descriptor.Descriptor(
  name='TaxCluster',
  full_name='taxcl.TaxCluster',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tax_cluster_id', full_name='taxcl.TaxCluster.tax_cluster_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='taxcl.TaxCluster.index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='menu_card_id', full_name='taxcl.TaxCluster.menu_card_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='local_name', full_name='taxcl.TaxCluster.local_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chinese_name', full_name='taxcl.TaxCluster.chinese_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=207,
)


_TAXCLUSTERLIST = _descriptor.Descriptor(
  name='TaxClusterList',
  full_name='taxcl.TaxClusterList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tax_cluster', full_name='taxcl.TaxClusterList.tax_cluster', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=265,
)

_TAXCLUSTERLIST.fields_by_name['tax_cluster'].message_type = _TAXCLUSTER
DESCRIPTOR.message_types_by_name['TaxClusterId'] = _TAXCLUSTERID
DESCRIPTOR.message_types_by_name['TaxCluster'] = _TAXCLUSTER
DESCRIPTOR.message_types_by_name['TaxClusterList'] = _TAXCLUSTERLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaxClusterId = _reflection.GeneratedProtocolMessageType('TaxClusterId', (_message.Message,), dict(
  DESCRIPTOR = _TAXCLUSTERID,
  __module__ = 'sql_tax_cluster_pb2'
  # @@protoc_insertion_point(class_scope:taxcl.TaxClusterId)
  ))
_sym_db.RegisterMessage(TaxClusterId)

TaxCluster = _reflection.GeneratedProtocolMessageType('TaxCluster', (_message.Message,), dict(
  DESCRIPTOR = _TAXCLUSTER,
  __module__ = 'sql_tax_cluster_pb2'
  # @@protoc_insertion_point(class_scope:taxcl.TaxCluster)
  ))
_sym_db.RegisterMessage(TaxCluster)

TaxClusterList = _reflection.GeneratedProtocolMessageType('TaxClusterList', (_message.Message,), dict(
  DESCRIPTOR = _TAXCLUSTERLIST,
  __module__ = 'sql_tax_cluster_pb2'
  # @@protoc_insertion_point(class_scope:taxcl.TaxClusterList)
  ))
_sym_db.RegisterMessage(TaxClusterList)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\023com.hha.tax.clusterP\001'))

_TAXCLUSTERSERVICE = _descriptor.ServiceDescriptor(
  name='TaxClusterService',
  full_name='taxcl.TaxClusterService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=268,
  serialized_end=759,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTaxClusters',
    full_name='taxcl.TaxClusterService.GetTaxClusters',
    index=0,
    containing_service=None,
    input_type=common__types__pb2._EMPTY,
    output_type=_TAXCLUSTERLIST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='EraseTaxCluster',
    full_name='taxcl.TaxClusterService.EraseTaxCluster',
    index=1,
    containing_service=None,
    input_type=_TAXCLUSTERID,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTaxCluster',
    full_name='taxcl.TaxClusterService.UpdateTaxCluster',
    index=2,
    containing_service=None,
    input_type=_TAXCLUSTER,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DuplicateTaxCluster',
    full_name='taxcl.TaxClusterService.DuplicateTaxCluster',
    index=3,
    containing_service=None,
    input_type=_TAXCLUSTERID,
    output_type=_TAXCLUSTERID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LowestTaxCluster',
    full_name='taxcl.TaxClusterService.LowestTaxCluster',
    index=4,
    containing_service=None,
    input_type=common__types__pb2._EMPTY,
    output_type=_TAXCLUSTERID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HighestTaxCluster',
    full_name='taxcl.TaxClusterService.HighestTaxCluster',
    index=5,
    containing_service=None,
    input_type=common__types__pb2._EMPTY,
    output_type=_TAXCLUSTERID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTaxCluster',
    full_name='taxcl.TaxClusterService.GetTaxCluster',
    index=6,
    containing_service=None,
    input_type=_TAXCLUSTERID,
    output_type=_TAXCLUSTER,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='InsertTaxCluster',
    full_name='taxcl.TaxClusterService.InsertTaxCluster',
    index=7,
    containing_service=None,
    input_type=common__types__pb2._EMPTY,
    output_type=_TAXCLUSTERID,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TAXCLUSTERSERVICE)

DESCRIPTOR.services_by_name['TaxClusterService'] = _TAXCLUSTERSERVICE

# @@protoc_insertion_point(module_scope)
