# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_types_pb2 as common__types__pb2
import sql_message_pb2 as sql__message__pb2


class MessageServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetValueById = channel.unary_unary(
        '/msg.MessageService/GetValueById',
        request_serializer=sql__message__pb2.GetValueByIdRequest.SerializeToString,
        response_deserializer=sql__message__pb2.GetValueByIdResponse.FromString,
        )
    self.SetValueById = channel.unary_unary(
        '/msg.MessageService/SetValueById',
        request_serializer=sql__message__pb2.SetValueByIdRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.GetAllMessages = channel.unary_unary(
        '/msg.MessageService/GetAllMessages',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=sql__message__pb2.GetAllMessagesResponse.FromString,
        )
    self.BackupMessages = channel.unary_unary(
        '/msg.MessageService/BackupMessages',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.RestoreMessages = channel.unary_unary(
        '/msg.MessageService/RestoreMessages',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )


class MessageServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetValueById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetValueById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllMessages(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BackupMessages(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RestoreMessages(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetValueById': grpc.unary_unary_rpc_method_handler(
          servicer.GetValueById,
          request_deserializer=sql__message__pb2.GetValueByIdRequest.FromString,
          response_serializer=sql__message__pb2.GetValueByIdResponse.SerializeToString,
      ),
      'SetValueById': grpc.unary_unary_rpc_method_handler(
          servicer.SetValueById,
          request_deserializer=sql__message__pb2.SetValueByIdRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'GetAllMessages': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllMessages,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=sql__message__pb2.GetAllMessagesResponse.SerializeToString,
      ),
      'BackupMessages': grpc.unary_unary_rpc_method_handler(
          servicer.BackupMessages,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'RestoreMessages': grpc.unary_unary_rpc_method_handler(
          servicer.RestoreMessages,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'msg.MessageService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
