# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sql_advertisement.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_types_pb2 as common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sql_advertisement.proto',
  package='ads',
  syntax='proto3',
  serialized_pb=_b('\n\x17sql_advertisement.proto\x12\x03\x61\x64s\x1a\x12\x63ommon_types.proto\"\xab\x02\n\rAdvertisement\x12\x13\n\x0b\x64\x61tabase_id\x18\x01 \x01(\x05\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.ads.Timing\x12\x0f\n\x07picture\x18\x03 \x01(\t\x12\x0b\n\x03top\x18\x04 \x01(\t\x12\x0e\n\x06\x63\x65nter\x18\x05 \x01(\t\x12\x12\n\nlocal_name\x18\x06 \x01(\t\x12\x14\n\x0c\x63hinese_name\x18\x07 \x01(\t\x12\x0e\n\x06\x62ottom\x18\x08 \x03(\t\x12\x12\n\ntop_colour\x18\t \x01(\x05\x12\x15\n\rcenter_colour\x18\n \x01(\x05\x12\x15\n\rbottom_colour\x18\x0b \x03(\x05\x12\r\n\x05start\x18\x0c \x01(\t\x12\x0b\n\x03\x65nd\x18\r \x01(\t\x12\x12\n\nstart_hour\x18\x0e \x03(\x05\x12\x10\n\x08hour_end\x18\x0f \x03(\x05\">\n\x11\x41\x64vertisementList\x12)\n\radvertisement\x18\x01 \x03(\x0b\x32\x12.ads.Advertisement*\x8c\x01\n\x06Timing\x12\x0c\n\x08\x41\x44\x44_NONE\x10\x00\x12\x17\n\x13\x41\x44\x44_DURING_TAKEAWAY\x10\x01\x12\x19\n\x15\x41\x44\x44_DURING_RESTAURANT\x10\x02\x12\x16\n\x12\x41\x44\x44_AFTER_TAKEAWAY\x10\x03\x12\x18\n\x14\x41\x44\x44_AFTER_RESTAURANT\x10\x04\x12\x0e\n\nADD_NORMAL\x10\x05\x32\x90\x02\n\x14\x41\x64vertisementService\x12?\n\x14GetAdvertisementList\x12\r.common.Empty\x1a\x16.ads.AdvertisementList\"\x00\x12\x42\n\x17UpdateAdvertisementList\x12\x16.ads.AdvertisementList\x1a\r.common.Empty\"\x00\x12:\n\x13UpdateAdvertisement\x12\x12.ads.Advertisement\x1a\r.common.Empty\"\x00\x12\x37\n\x10NewAdvertisement\x12\r.common.Empty\x1a\x12.ads.Advertisement\"\x00\x42\'\n\x15\x63om.hha.advertisementP\x01\xaa\x02\x0bGrpcServiceb\x06proto3')
  ,
  dependencies=[common__types__pb2.DESCRIPTOR,])

_TIMING = _descriptor.EnumDescriptor(
  name='Timing',
  full_name='ads.Timing',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADD_NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD_DURING_TAKEAWAY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD_DURING_RESTAURANT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD_AFTER_TAKEAWAY', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD_AFTER_RESTAURANT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD_NORMAL', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=419,
  serialized_end=559,
)
_sym_db.RegisterEnumDescriptor(_TIMING)

Timing = enum_type_wrapper.EnumTypeWrapper(_TIMING)
ADD_NONE = 0
ADD_DURING_TAKEAWAY = 1
ADD_DURING_RESTAURANT = 2
ADD_AFTER_TAKEAWAY = 3
ADD_AFTER_RESTAURANT = 4
ADD_NORMAL = 5



_ADVERTISEMENT = _descriptor.Descriptor(
  name='Advertisement',
  full_name='ads.Advertisement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database_id', full_name='ads.Advertisement.database_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ads.Advertisement.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='picture', full_name='ads.Advertisement.picture', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top', full_name='ads.Advertisement.top', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='center', full_name='ads.Advertisement.center', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='local_name', full_name='ads.Advertisement.local_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chinese_name', full_name='ads.Advertisement.chinese_name', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bottom', full_name='ads.Advertisement.bottom', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top_colour', full_name='ads.Advertisement.top_colour', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='center_colour', full_name='ads.Advertisement.center_colour', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bottom_colour', full_name='ads.Advertisement.bottom_colour', index=10,
      number=11, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='ads.Advertisement.start', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='ads.Advertisement.end', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_hour', full_name='ads.Advertisement.start_hour', index=13,
      number=14, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hour_end', full_name='ads.Advertisement.hour_end', index=14,
      number=15, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=352,
)


_ADVERTISEMENTLIST = _descriptor.Descriptor(
  name='AdvertisementList',
  full_name='ads.AdvertisementList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='advertisement', full_name='ads.AdvertisementList.advertisement', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=416,
)

_ADVERTISEMENT.fields_by_name['type'].enum_type = _TIMING
_ADVERTISEMENTLIST.fields_by_name['advertisement'].message_type = _ADVERTISEMENT
DESCRIPTOR.message_types_by_name['Advertisement'] = _ADVERTISEMENT
DESCRIPTOR.message_types_by_name['AdvertisementList'] = _ADVERTISEMENTLIST
DESCRIPTOR.enum_types_by_name['Timing'] = _TIMING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Advertisement = _reflection.GeneratedProtocolMessageType('Advertisement', (_message.Message,), dict(
  DESCRIPTOR = _ADVERTISEMENT,
  __module__ = 'sql_advertisement_pb2'
  # @@protoc_insertion_point(class_scope:ads.Advertisement)
  ))
_sym_db.RegisterMessage(Advertisement)

AdvertisementList = _reflection.GeneratedProtocolMessageType('AdvertisementList', (_message.Message,), dict(
  DESCRIPTOR = _ADVERTISEMENTLIST,
  __module__ = 'sql_advertisement_pb2'
  # @@protoc_insertion_point(class_scope:ads.AdvertisementList)
  ))
_sym_db.RegisterMessage(AdvertisementList)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025com.hha.advertisementP\001\252\002\013GrpcService'))

_ADVERTISEMENTSERVICE = _descriptor.ServiceDescriptor(
  name='AdvertisementService',
  full_name='ads.AdvertisementService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=562,
  serialized_end=834,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAdvertisementList',
    full_name='ads.AdvertisementService.GetAdvertisementList',
    index=0,
    containing_service=None,
    input_type=common__types__pb2._EMPTY,
    output_type=_ADVERTISEMENTLIST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateAdvertisementList',
    full_name='ads.AdvertisementService.UpdateAdvertisementList',
    index=1,
    containing_service=None,
    input_type=_ADVERTISEMENTLIST,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateAdvertisement',
    full_name='ads.AdvertisementService.UpdateAdvertisement',
    index=2,
    containing_service=None,
    input_type=_ADVERTISEMENT,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='NewAdvertisement',
    full_name='ads.AdvertisementService.NewAdvertisement',
    index=3,
    containing_service=None,
    input_type=common__types__pb2._EMPTY,
    output_type=_ADVERTISEMENT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADVERTISEMENTSERVICE)

DESCRIPTOR.services_by_name['AdvertisementService'] = _ADVERTISEMENTSERVICE

# @@protoc_insertion_point(module_scope)
