# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_types_pb2 as common__types__pb2
import sql_tax_pb2 as sql__tax__pb2


class TaxServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SetRate = channel.unary_unary(
        '/tax.TaxService/SetRate',
        request_serializer=sql__tax__pb2.SetRateRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.GetName = channel.unary_unary(
        '/tax.TaxService/GetName',
        request_serializer=sql__tax__pb2.GetNameRequest.SerializeToString,
        response_deserializer=sql__tax__pb2.GetNameResponse.FromString,
        )
    self.Verify = channel.unary_unary(
        '/tax.TaxService/Verify',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=sql__tax__pb2.VerifyResponse.FromString,
        )
    self.GetRate = channel.unary_unary(
        '/tax.TaxService/GetRate',
        request_serializer=sql__tax__pb2.GetRateRequest.SerializeToString,
        response_deserializer=sql__tax__pb2.GetRateResponse.FromString,
        )
    self.Dump = channel.unary_unary(
        '/tax.TaxService/Dump',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=sql__tax__pb2.DumpResponse.FromString,
        )


class TaxServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SetRate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Verify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Dump(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TaxServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SetRate': grpc.unary_unary_rpc_method_handler(
          servicer.SetRate,
          request_deserializer=sql__tax__pb2.SetRateRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'GetName': grpc.unary_unary_rpc_method_handler(
          servicer.GetName,
          request_deserializer=sql__tax__pb2.GetNameRequest.FromString,
          response_serializer=sql__tax__pb2.GetNameResponse.SerializeToString,
      ),
      'Verify': grpc.unary_unary_rpc_method_handler(
          servicer.Verify,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=sql__tax__pb2.VerifyResponse.SerializeToString,
      ),
      'GetRate': grpc.unary_unary_rpc_method_handler(
          servicer.GetRate,
          request_deserializer=sql__tax__pb2.GetRateRequest.FromString,
          response_serializer=sql__tax__pb2.GetRateResponse.SerializeToString,
      ),
      'Dump': grpc.unary_unary_rpc_method_handler(
          servicer.Dump,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=sql__tax__pb2.DumpResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tax.TaxService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
