# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sql_archive_wallet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_types_pb2 as common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sql_archive_wallet.proto',
  package='aw',
  syntax='proto3',
  serialized_pb=_b('\n\x18sql_archive_wallet.proto\x12\x02\x61w\x1a\x12\x63ommon_types.proto\"\x1e\n\x07RfidKey\x12\x13\n\x0brfid_key_id\x18\x01 \x01(\x05\x32N\n\x14\x41rchiveWalletService\x12\x36\n\x16\x41rchiveWalletForPerson\x12\x0b.aw.RfidKey\x1a\r.common.Empty\"\x00\x42(\n\x16\x63om.hha.archive.walletP\x01\xaa\x02\x0bGrpcServiceb\x06proto3')
  ,
  dependencies=[common__types__pb2.DESCRIPTOR,])




_RFIDKEY = _descriptor.Descriptor(
  name='RfidKey',
  full_name='aw.RfidKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rfid_key_id', full_name='aw.RfidKey.rfid_key_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['RfidKey'] = _RFIDKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RfidKey = _reflection.GeneratedProtocolMessageType('RfidKey', (_message.Message,), dict(
  DESCRIPTOR = _RFIDKEY,
  __module__ = 'sql_archive_wallet_pb2'
  # @@protoc_insertion_point(class_scope:aw.RfidKey)
  ))
_sym_db.RegisterMessage(RfidKey)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026com.hha.archive.walletP\001\252\002\013GrpcService'))

_ARCHIVEWALLETSERVICE = _descriptor.ServiceDescriptor(
  name='ArchiveWalletService',
  full_name='aw.ArchiveWalletService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=84,
  serialized_end=162,
  methods=[
  _descriptor.MethodDescriptor(
    name='ArchiveWalletForPerson',
    full_name='aw.ArchiveWalletService.ArchiveWalletForPerson',
    index=0,
    containing_service=None,
    input_type=_RFIDKEY,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARCHIVEWALLETSERVICE)

DESCRIPTOR.services_by_name['ArchiveWalletService'] = _ARCHIVEWALLETSERVICE

# @@protoc_insertion_point(module_scope)
