# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_types_pb2 as common__types__pb2
import sql_store_transaction_item_pb2 as sql__store__transaction__item__pb2


class storeTransactionItemServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.InsertOrder = channel.unary_unary(
        '/sti.storeTransactionItemService/InsertOrder',
        request_serializer=sql__store__transaction__item__pb2.StoreOrder.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.SelectSmurf = channel.unary_unary(
        '/sti.storeTransactionItemService/SelectSmurf',
        request_serializer=sql__store__transaction__item__pb2.StoreSmurfId.SerializeToString,
        response_deserializer=sql__store__transaction__item__pb2.StoreOrderList.FromString,
        )
    self.AddStoreItem = channel.unary_unary(
        '/sti.storeTransactionItemService/AddStoreItem',
        request_serializer=common__types__pb2.StorePart.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.SetState = channel.unary_unary(
        '/sti.storeTransactionItemService/SetState',
        request_serializer=sql__store__transaction__item__pb2.SetStateRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.GetSmurfTotals = channel.unary_unary(
        '/sti.storeTransactionItemService/GetSmurfTotals',
        request_serializer=sql__store__transaction__item__pb2.StoreSmurfId.SerializeToString,
        response_deserializer=sql__store__transaction__item__pb2.TotalStore.FromString,
        )
    self.GetStatistics = channel.unary_unary(
        '/sti.storeTransactionItemService/GetStatistics',
        request_serializer=sql__store__transaction__item__pb2.MenuItemId.SerializeToString,
        response_deserializer=sql__store__transaction__item__pb2.StoreStat.FromString,
        )
    self.DeliveryDone = channel.unary_unary(
        '/sti.storeTransactionItemService/DeliveryDone',
        request_serializer=sql__store__transaction__item__pb2.DeliveryStateRequest.SerializeToString,
        response_deserializer=sql__store__transaction__item__pb2.DeliveryResponse.FromString,
        )
    self.DeliveryLate = channel.unary_unary(
        '/sti.storeTransactionItemService/DeliveryLate',
        request_serializer=sql__store__transaction__item__pb2.DeliveryStateRequest.SerializeToString,
        response_deserializer=sql__store__transaction__item__pb2.DeliveryResponse.FromString,
        )
    self.DeliveryCancel = channel.unary_unary(
        '/sti.storeTransactionItemService/DeliveryCancel',
        request_serializer=sql__store__transaction__item__pb2.DeliveryStateRequest.SerializeToString,
        response_deserializer=sql__store__transaction__item__pb2.DeliveryResponse.FromString,
        )
    self.DeliveryNext = channel.unary_unary(
        '/sti.storeTransactionItemService/DeliveryNext',
        request_serializer=sql__store__transaction__item__pb2.DeliveryStateRequest.SerializeToString,
        response_deserializer=sql__store__transaction__item__pb2.DeliveryResponse.FromString,
        )


class storeTransactionItemServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def InsertOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SelectSmurf(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddStoreItem(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSmurfTotals(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStatistics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeliveryDone(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeliveryLate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeliveryCancel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeliveryNext(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_storeTransactionItemServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'InsertOrder': grpc.unary_unary_rpc_method_handler(
          servicer.InsertOrder,
          request_deserializer=sql__store__transaction__item__pb2.StoreOrder.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'SelectSmurf': grpc.unary_unary_rpc_method_handler(
          servicer.SelectSmurf,
          request_deserializer=sql__store__transaction__item__pb2.StoreSmurfId.FromString,
          response_serializer=sql__store__transaction__item__pb2.StoreOrderList.SerializeToString,
      ),
      'AddStoreItem': grpc.unary_unary_rpc_method_handler(
          servicer.AddStoreItem,
          request_deserializer=common__types__pb2.StorePart.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'SetState': grpc.unary_unary_rpc_method_handler(
          servicer.SetState,
          request_deserializer=sql__store__transaction__item__pb2.SetStateRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'GetSmurfTotals': grpc.unary_unary_rpc_method_handler(
          servicer.GetSmurfTotals,
          request_deserializer=sql__store__transaction__item__pb2.StoreSmurfId.FromString,
          response_serializer=sql__store__transaction__item__pb2.TotalStore.SerializeToString,
      ),
      'GetStatistics': grpc.unary_unary_rpc_method_handler(
          servicer.GetStatistics,
          request_deserializer=sql__store__transaction__item__pb2.MenuItemId.FromString,
          response_serializer=sql__store__transaction__item__pb2.StoreStat.SerializeToString,
      ),
      'DeliveryDone': grpc.unary_unary_rpc_method_handler(
          servicer.DeliveryDone,
          request_deserializer=sql__store__transaction__item__pb2.DeliveryStateRequest.FromString,
          response_serializer=sql__store__transaction__item__pb2.DeliveryResponse.SerializeToString,
      ),
      'DeliveryLate': grpc.unary_unary_rpc_method_handler(
          servicer.DeliveryLate,
          request_deserializer=sql__store__transaction__item__pb2.DeliveryStateRequest.FromString,
          response_serializer=sql__store__transaction__item__pb2.DeliveryResponse.SerializeToString,
      ),
      'DeliveryCancel': grpc.unary_unary_rpc_method_handler(
          servicer.DeliveryCancel,
          request_deserializer=sql__store__transaction__item__pb2.DeliveryStateRequest.FromString,
          response_serializer=sql__store__transaction__item__pb2.DeliveryResponse.SerializeToString,
      ),
      'DeliveryNext': grpc.unary_unary_rpc_method_handler(
          servicer.DeliveryNext,
          request_deserializer=sql__store__transaction__item__pb2.DeliveryStateRequest.FromString,
          response_serializer=sql__store__transaction__item__pb2.DeliveryResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sti.storeTransactionItemService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
