# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_types_pb2 as common__types__pb2
import sql_menu_cluster_item_pb2 as sql__menu__cluster__item__pb2


class MenuClusterItemServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BackupClusterItems = channel.unary_unary(
        '/mci.MenuClusterItemService/BackupClusterItems',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.DeleteClusterItem = channel.unary_unary(
        '/mci.MenuClusterItemService/DeleteClusterItem',
        request_serializer=sql__menu__cluster__item__pb2.DeleteClusterItemRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.DuplicateClusterItem = channel.unary_unary(
        '/mci.MenuClusterItemService/DuplicateClusterItem',
        request_serializer=sql__menu__cluster__item__pb2.DuplicateClusterItemRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.DuplicateMenuCard = channel.unary_unary(
        '/mci.MenuClusterItemService/DuplicateMenuCard',
        request_serializer=sql__menu__cluster__item__pb2.DuplicateMenuCardRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.ExchangeCluster = channel.unary_unary(
        '/mci.MenuClusterItemService/ExchangeCluster',
        request_serializer=sql__menu__cluster__item__pb2.ExchangeClusterRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.FindAllExcelItems = channel.unary_unary(
        '/mci.MenuClusterItemService/FindAllExcelItems',
        request_serializer=sql__menu__cluster__item__pb2.MenuCardId.SerializeToString,
        response_deserializer=sql__menu__cluster__item__pb2.ClusterItemList.FromString,
        )
    self.GetSize = channel.unary_unary(
        '/mci.MenuClusterItemService/GetSize',
        request_serializer=sql__menu__cluster__item__pb2.MenuCardId.SerializeToString,
        response_deserializer=sql__menu__cluster__item__pb2.ClusterItemSize.FromString,
        )
    self.InsertClusterItem = channel.unary_unary(
        '/mci.MenuClusterItemService/InsertClusterItem',
        request_serializer=sql__menu__cluster__item__pb2.InsertClusterItemRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.MysqlDump = channel.unary_unary(
        '/mci.MenuClusterItemService/MysqlDump',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=sql__menu__cluster__item__pb2.TextDump.FromString,
        )
    self.SaveAllClusterItems = channel.unary_unary(
        '/mci.MenuClusterItemService/SaveAllClusterItems',
        request_serializer=sql__menu__cluster__item__pb2.SaveClusterItemsRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.SelectClusterItems = channel.unary_unary(
        '/mci.MenuClusterItemService/SelectClusterItems',
        request_serializer=sql__menu__cluster__item__pb2.ClusterIdRequest.SerializeToString,
        response_deserializer=sql__menu__cluster__item__pb2.ClusterItemList.FromString,
        )
    self.UpdateClusterItem = channel.unary_unary(
        '/mci.MenuClusterItemService/UpdateClusterItem',
        request_serializer=sql__menu__cluster__item__pb2.ClusterItem.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.RenumberClusterItems = channel.unary_unary(
        '/mci.MenuClusterItemService/RenumberClusterItems',
        request_serializer=sql__menu__cluster__item__pb2.MenuCardId.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.RemoveAllClusterItemsFromMenuCard = channel.unary_unary(
        '/mci.MenuClusterItemService/RemoveAllClusterItemsFromMenuCard',
        request_serializer=sql__menu__cluster__item__pb2.MenuCardId.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.RestoreClusterItems = channel.unary_unary(
        '/mci.MenuClusterItemService/RestoreClusterItems',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )


class MenuClusterItemServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def BackupClusterItems(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteClusterItem(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DuplicateClusterItem(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DuplicateMenuCard(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExchangeCluster(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindAllExcelItems(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InsertClusterItem(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MysqlDump(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveAllClusterItems(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SelectClusterItems(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateClusterItem(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RenumberClusterItems(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveAllClusterItemsFromMenuCard(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RestoreClusterItems(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MenuClusterItemServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BackupClusterItems': grpc.unary_unary_rpc_method_handler(
          servicer.BackupClusterItems,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'DeleteClusterItem': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteClusterItem,
          request_deserializer=sql__menu__cluster__item__pb2.DeleteClusterItemRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'DuplicateClusterItem': grpc.unary_unary_rpc_method_handler(
          servicer.DuplicateClusterItem,
          request_deserializer=sql__menu__cluster__item__pb2.DuplicateClusterItemRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'DuplicateMenuCard': grpc.unary_unary_rpc_method_handler(
          servicer.DuplicateMenuCard,
          request_deserializer=sql__menu__cluster__item__pb2.DuplicateMenuCardRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'ExchangeCluster': grpc.unary_unary_rpc_method_handler(
          servicer.ExchangeCluster,
          request_deserializer=sql__menu__cluster__item__pb2.ExchangeClusterRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'FindAllExcelItems': grpc.unary_unary_rpc_method_handler(
          servicer.FindAllExcelItems,
          request_deserializer=sql__menu__cluster__item__pb2.MenuCardId.FromString,
          response_serializer=sql__menu__cluster__item__pb2.ClusterItemList.SerializeToString,
      ),
      'GetSize': grpc.unary_unary_rpc_method_handler(
          servicer.GetSize,
          request_deserializer=sql__menu__cluster__item__pb2.MenuCardId.FromString,
          response_serializer=sql__menu__cluster__item__pb2.ClusterItemSize.SerializeToString,
      ),
      'InsertClusterItem': grpc.unary_unary_rpc_method_handler(
          servicer.InsertClusterItem,
          request_deserializer=sql__menu__cluster__item__pb2.InsertClusterItemRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'MysqlDump': grpc.unary_unary_rpc_method_handler(
          servicer.MysqlDump,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=sql__menu__cluster__item__pb2.TextDump.SerializeToString,
      ),
      'SaveAllClusterItems': grpc.unary_unary_rpc_method_handler(
          servicer.SaveAllClusterItems,
          request_deserializer=sql__menu__cluster__item__pb2.SaveClusterItemsRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'SelectClusterItems': grpc.unary_unary_rpc_method_handler(
          servicer.SelectClusterItems,
          request_deserializer=sql__menu__cluster__item__pb2.ClusterIdRequest.FromString,
          response_serializer=sql__menu__cluster__item__pb2.ClusterItemList.SerializeToString,
      ),
      'UpdateClusterItem': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateClusterItem,
          request_deserializer=sql__menu__cluster__item__pb2.ClusterItem.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'RenumberClusterItems': grpc.unary_unary_rpc_method_handler(
          servicer.RenumberClusterItems,
          request_deserializer=sql__menu__cluster__item__pb2.MenuCardId.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'RemoveAllClusterItemsFromMenuCard': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveAllClusterItemsFromMenuCard,
          request_deserializer=sql__menu__cluster__item__pb2.MenuCardId.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'RestoreClusterItems': grpc.unary_unary_rpc_method_handler(
          servicer.RestoreClusterItems,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'mci.MenuClusterItemService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
