# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_types_pb2 as common__types__pb2
import sql_personnel_pb2 as sql__personnel__pb2


class PersonnelServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPersonById = channel.unary_unary(
        '/prs.PersonnelService/GetPersonById',
        request_serializer=sql__personnel__pb2.PersonId.SerializeToString,
        response_deserializer=sql__personnel__pb2.Person.FromString,
        )
    self.GetPersonByDongle = channel.unary_unary(
        '/prs.PersonnelService/GetPersonByDongle',
        request_serializer=sql__personnel__pb2.DongleId.SerializeToString,
        response_deserializer=sql__personnel__pb2.Person.FromString,
        )
    self.GetAllPersons = channel.unary_unary(
        '/prs.PersonnelService/GetAllPersons',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=sql__personnel__pb2.PersonList.FromString,
        )
    self.UpdatePerson = channel.unary_unary(
        '/prs.PersonnelService/UpdatePerson',
        request_serializer=sql__personnel__pb2.PersonComplete.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.GetNewKey = channel.unary_unary(
        '/prs.PersonnelService/GetNewKey',
        request_serializer=sql__personnel__pb2.DongleRestaurantRequest.SerializeToString,
        response_deserializer=sql__personnel__pb2.Person.FromString,
        )
    self.ClearDatabaseKey = channel.unary_unary(
        '/prs.PersonnelService/ClearDatabaseKey',
        request_serializer=sql__personnel__pb2.PersonId.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.IsValid = channel.unary_unary(
        '/prs.PersonnelService/IsValid',
        request_serializer=sql__personnel__pb2.PersonId.SerializeToString,
        response_deserializer=sql__personnel__pb2.IsValidKey.FromString,
        )
    self.GetAccess = channel.unary_unary(
        '/prs.PersonnelService/GetAccess',
        request_serializer=sql__personnel__pb2.PersonId.SerializeToString,
        response_deserializer=sql__personnel__pb2.AccessReply.FromString,
        )


class PersonnelServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPersonById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPersonByDongle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllPersons(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdatePerson(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNewKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ClearDatabaseKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IsValid(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAccess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PersonnelServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPersonById': grpc.unary_unary_rpc_method_handler(
          servicer.GetPersonById,
          request_deserializer=sql__personnel__pb2.PersonId.FromString,
          response_serializer=sql__personnel__pb2.Person.SerializeToString,
      ),
      'GetPersonByDongle': grpc.unary_unary_rpc_method_handler(
          servicer.GetPersonByDongle,
          request_deserializer=sql__personnel__pb2.DongleId.FromString,
          response_serializer=sql__personnel__pb2.Person.SerializeToString,
      ),
      'GetAllPersons': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllPersons,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=sql__personnel__pb2.PersonList.SerializeToString,
      ),
      'UpdatePerson': grpc.unary_unary_rpc_method_handler(
          servicer.UpdatePerson,
          request_deserializer=sql__personnel__pb2.PersonComplete.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'GetNewKey': grpc.unary_unary_rpc_method_handler(
          servicer.GetNewKey,
          request_deserializer=sql__personnel__pb2.DongleRestaurantRequest.FromString,
          response_serializer=sql__personnel__pb2.Person.SerializeToString,
      ),
      'ClearDatabaseKey': grpc.unary_unary_rpc_method_handler(
          servicer.ClearDatabaseKey,
          request_deserializer=sql__personnel__pb2.PersonId.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'IsValid': grpc.unary_unary_rpc_method_handler(
          servicer.IsValid,
          request_deserializer=sql__personnel__pb2.PersonId.FromString,
          response_serializer=sql__personnel__pb2.IsValidKey.SerializeToString,
      ),
      'GetAccess': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccess,
          request_deserializer=sql__personnel__pb2.PersonId.FromString,
          response_serializer=sql__personnel__pb2.AccessReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'prs.PersonnelService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
