# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_types_pb2 as common__types__pb2
import sql_floor_table_pb2 as sql__floor__table__pb2


class FloorTableServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.UpdateTable = channel.unary_unary(
        '/ft.FloorTableService/UpdateTable',
        request_serializer=sql__floor__table__pb2.Table.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.Smaller = channel.unary_unary(
        '/ft.FloorTableService/Smaller',
        request_serializer=sql__floor__table__pb2.TableIdParam.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.Lower = channel.unary_unary(
        '/ft.FloorTableService/Lower',
        request_serializer=sql__floor__table__pb2.TableIdParam.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.Wider = channel.unary_unary(
        '/ft.FloorTableService/Wider',
        request_serializer=sql__floor__table__pb2.TableIdDisplaySizeParam.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.Higher = channel.unary_unary(
        '/ft.FloorTableService/Higher',
        request_serializer=sql__floor__table__pb2.TableIdDisplaySizeParam.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.SetPersons = channel.unary_unary(
        '/ft.FloorTableService/SetPersons',
        request_serializer=sql__floor__table__pb2.PersonsParam.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.SetName = channel.unary_unary(
        '/ft.FloorTableService/SetName',
        request_serializer=sql__floor__table__pb2.NameParam.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.GetName = channel.unary_unary(
        '/ft.FloorTableService/GetName',
        request_serializer=sql__floor__table__pb2.TableIdParam.SerializeToString,
        response_deserializer=sql__floor__table__pb2.NameParam.FromString,
        )
    self.GetFloorTables = channel.unary_unary(
        '/ft.FloorTableService/GetFloorTables',
        request_serializer=sql__floor__table__pb2.FloorPlanOnlyOpen.SerializeToString,
        response_deserializer=sql__floor__table__pb2.TableList.FromString,
        )
    self.CreateTable = channel.unary_unary(
        '/ft.FloorTableService/CreateTable',
        request_serializer=sql__floor__table__pb2.CreateTableRequest.SerializeToString,
        response_deserializer=sql__floor__table__pb2.Table.FromString,
        )
    self.FindAny = channel.unary_unary(
        '/ft.FloorTableService/FindAny',
        request_serializer=sql__floor__table__pb2.NameValueParam.SerializeToString,
        response_deserializer=sql__floor__table__pb2.TableIdParam.FromString,
        )
    self.TableExists = channel.unary_unary(
        '/ft.FloorTableService/TableExists',
        request_serializer=sql__floor__table__pb2.NameValueParam.SerializeToString,
        response_deserializer=sql__floor__table__pb2.TableExist.FromString,
        )
    self.FindNewTableNumber = channel.unary_unary(
        '/ft.FloorTableService/FindNewTableNumber',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=sql__floor__table__pb2.NameValueParam.FromString,
        )
    self.RemoveBeerDrinker = channel.unary_unary(
        '/ft.FloorTableService/RemoveBeerDrinker',
        request_serializer=sql__floor__table__pb2.NameValueParam.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.ConnectTableToTransaction = channel.unary_unary(
        '/ft.FloorTableService/ConnectTableToTransaction',
        request_serializer=sql__floor__table__pb2.ConnectFloorTable.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.CloseTransaction = channel.unary_unary(
        '/ft.FloorTableService/CloseTransaction',
        request_serializer=sql__floor__table__pb2.TransactionIdParam.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.MoveTransactionAndName = channel.unary_unary(
        '/ft.FloorTableService/MoveTransactionAndName',
        request_serializer=sql__floor__table__pb2.MoveTableAndNameParam.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.MoveTransaction = channel.unary_unary(
        '/ft.FloorTableService/MoveTransaction',
        request_serializer=sql__floor__table__pb2.TransactionToTableParam.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.AddTransaction = channel.unary_unary(
        '/ft.FloorTableService/AddTransaction',
        request_serializer=sql__floor__table__pb2.TransactionToTableParam.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.ExtendLatestTable = channel.unary_unary(
        '/ft.FloorTableService/ExtendLatestTable',
        request_serializer=sql__floor__table__pb2.NameValueParam.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.GetFloorTableById = channel.unary_unary(
        '/ft.FloorTableService/GetFloorTableById',
        request_serializer=sql__floor__table__pb2.TableIdParam.SerializeToString,
        response_deserializer=sql__floor__table__pb2.Table.FromString,
        )
    self.GetFloorTableByName = channel.unary_unary(
        '/ft.FloorTableService/GetFloorTableByName',
        request_serializer=sql__floor__table__pb2.NameValueParam.SerializeToString,
        response_deserializer=sql__floor__table__pb2.Table.FromString,
        )
    self.GetFloorTableFromKeybutton = channel.unary_unary(
        '/ft.FloorTableService/GetFloorTableFromKeybutton',
        request_serializer=sql__floor__table__pb2.KeybuttonParam.SerializeToString,
        response_deserializer=sql__floor__table__pb2.Table.FromString,
        )
    self.AddMinutes = channel.unary_unary(
        '/ft.FloorTableService/AddMinutes',
        request_serializer=sql__floor__table__pb2.TableMinutesParam.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.UpdateData = channel.unary_unary(
        '/ft.FloorTableService/UpdateData',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.Rename = channel.unary_unary(
        '/ft.FloorTableService/Rename',
        request_serializer=sql__floor__table__pb2.NameParam.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.FindTable = channel.unary_unary(
        '/ft.FloorTableService/FindTable',
        request_serializer=sql__floor__table__pb2.NameValueParam.SerializeToString,
        response_deserializer=sql__floor__table__pb2.Table.FromString,
        )
    self.SetStatus = channel.unary_unary(
        '/ft.FloorTableService/SetStatus',
        request_serializer=sql__floor__table__pb2.TableIdStatusParam.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.UpdateDrinksMinutes = channel.unary_unary(
        '/ft.FloorTableService/UpdateDrinksMinutes',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.GetTableIdFromTransactionId = channel.unary_unary(
        '/ft.FloorTableService/GetTableIdFromTransactionId',
        request_serializer=sql__floor__table__pb2.TransactionIdParam.SerializeToString,
        response_deserializer=sql__floor__table__pb2.TableIdParam.FromString,
        )
    self.MysqlDump = channel.unary_unary(
        '/ft.FloorTableService/MysqlDump',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=common__types__pb2.TextDump.FromString,
        )
    self.Destroy = channel.unary_unary(
        '/ft.FloorTableService/Destroy',
        request_serializer=sql__floor__table__pb2.TableIdParam.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.SetTransactionTableAvailable = channel.unary_unary(
        '/ft.FloorTableService/SetTransactionTableAvailable',
        request_serializer=sql__floor__table__pb2.TransactionIdParam.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )


class FloorTableServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def UpdateTable(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Smaller(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Lower(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Wider(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Higher(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetPersons(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFloorTables(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateTable(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindAny(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TableExists(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindNewTableNumber(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveBeerDrinker(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ConnectTableToTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CloseTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MoveTransactionAndName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MoveTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddTransaction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExtendLatestTable(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFloorTableById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFloorTableByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFloorTableFromKeybutton(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddMinutes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Rename(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindTable(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateDrinksMinutes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTableIdFromTransactionId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MysqlDump(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Destroy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetTransactionTableAvailable(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FloorTableServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'UpdateTable': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateTable,
          request_deserializer=sql__floor__table__pb2.Table.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'Smaller': grpc.unary_unary_rpc_method_handler(
          servicer.Smaller,
          request_deserializer=sql__floor__table__pb2.TableIdParam.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'Lower': grpc.unary_unary_rpc_method_handler(
          servicer.Lower,
          request_deserializer=sql__floor__table__pb2.TableIdParam.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'Wider': grpc.unary_unary_rpc_method_handler(
          servicer.Wider,
          request_deserializer=sql__floor__table__pb2.TableIdDisplaySizeParam.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'Higher': grpc.unary_unary_rpc_method_handler(
          servicer.Higher,
          request_deserializer=sql__floor__table__pb2.TableIdDisplaySizeParam.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'SetPersons': grpc.unary_unary_rpc_method_handler(
          servicer.SetPersons,
          request_deserializer=sql__floor__table__pb2.PersonsParam.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'SetName': grpc.unary_unary_rpc_method_handler(
          servicer.SetName,
          request_deserializer=sql__floor__table__pb2.NameParam.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'GetName': grpc.unary_unary_rpc_method_handler(
          servicer.GetName,
          request_deserializer=sql__floor__table__pb2.TableIdParam.FromString,
          response_serializer=sql__floor__table__pb2.NameParam.SerializeToString,
      ),
      'GetFloorTables': grpc.unary_unary_rpc_method_handler(
          servicer.GetFloorTables,
          request_deserializer=sql__floor__table__pb2.FloorPlanOnlyOpen.FromString,
          response_serializer=sql__floor__table__pb2.TableList.SerializeToString,
      ),
      'CreateTable': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTable,
          request_deserializer=sql__floor__table__pb2.CreateTableRequest.FromString,
          response_serializer=sql__floor__table__pb2.Table.SerializeToString,
      ),
      'FindAny': grpc.unary_unary_rpc_method_handler(
          servicer.FindAny,
          request_deserializer=sql__floor__table__pb2.NameValueParam.FromString,
          response_serializer=sql__floor__table__pb2.TableIdParam.SerializeToString,
      ),
      'TableExists': grpc.unary_unary_rpc_method_handler(
          servicer.TableExists,
          request_deserializer=sql__floor__table__pb2.NameValueParam.FromString,
          response_serializer=sql__floor__table__pb2.TableExist.SerializeToString,
      ),
      'FindNewTableNumber': grpc.unary_unary_rpc_method_handler(
          servicer.FindNewTableNumber,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=sql__floor__table__pb2.NameValueParam.SerializeToString,
      ),
      'RemoveBeerDrinker': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveBeerDrinker,
          request_deserializer=sql__floor__table__pb2.NameValueParam.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'ConnectTableToTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.ConnectTableToTransaction,
          request_deserializer=sql__floor__table__pb2.ConnectFloorTable.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'CloseTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.CloseTransaction,
          request_deserializer=sql__floor__table__pb2.TransactionIdParam.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'MoveTransactionAndName': grpc.unary_unary_rpc_method_handler(
          servicer.MoveTransactionAndName,
          request_deserializer=sql__floor__table__pb2.MoveTableAndNameParam.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'MoveTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.MoveTransaction,
          request_deserializer=sql__floor__table__pb2.TransactionToTableParam.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'AddTransaction': grpc.unary_unary_rpc_method_handler(
          servicer.AddTransaction,
          request_deserializer=sql__floor__table__pb2.TransactionToTableParam.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'ExtendLatestTable': grpc.unary_unary_rpc_method_handler(
          servicer.ExtendLatestTable,
          request_deserializer=sql__floor__table__pb2.NameValueParam.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'GetFloorTableById': grpc.unary_unary_rpc_method_handler(
          servicer.GetFloorTableById,
          request_deserializer=sql__floor__table__pb2.TableIdParam.FromString,
          response_serializer=sql__floor__table__pb2.Table.SerializeToString,
      ),
      'GetFloorTableByName': grpc.unary_unary_rpc_method_handler(
          servicer.GetFloorTableByName,
          request_deserializer=sql__floor__table__pb2.NameValueParam.FromString,
          response_serializer=sql__floor__table__pb2.Table.SerializeToString,
      ),
      'GetFloorTableFromKeybutton': grpc.unary_unary_rpc_method_handler(
          servicer.GetFloorTableFromKeybutton,
          request_deserializer=sql__floor__table__pb2.KeybuttonParam.FromString,
          response_serializer=sql__floor__table__pb2.Table.SerializeToString,
      ),
      'AddMinutes': grpc.unary_unary_rpc_method_handler(
          servicer.AddMinutes,
          request_deserializer=sql__floor__table__pb2.TableMinutesParam.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'UpdateData': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateData,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'Rename': grpc.unary_unary_rpc_method_handler(
          servicer.Rename,
          request_deserializer=sql__floor__table__pb2.NameParam.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'FindTable': grpc.unary_unary_rpc_method_handler(
          servicer.FindTable,
          request_deserializer=sql__floor__table__pb2.NameValueParam.FromString,
          response_serializer=sql__floor__table__pb2.Table.SerializeToString,
      ),
      'SetStatus': grpc.unary_unary_rpc_method_handler(
          servicer.SetStatus,
          request_deserializer=sql__floor__table__pb2.TableIdStatusParam.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'UpdateDrinksMinutes': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateDrinksMinutes,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'GetTableIdFromTransactionId': grpc.unary_unary_rpc_method_handler(
          servicer.GetTableIdFromTransactionId,
          request_deserializer=sql__floor__table__pb2.TransactionIdParam.FromString,
          response_serializer=sql__floor__table__pb2.TableIdParam.SerializeToString,
      ),
      'MysqlDump': grpc.unary_unary_rpc_method_handler(
          servicer.MysqlDump,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=common__types__pb2.TextDump.SerializeToString,
      ),
      'Destroy': grpc.unary_unary_rpc_method_handler(
          servicer.Destroy,
          request_deserializer=sql__floor__table__pb2.TableIdParam.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'SetTransactionTableAvailable': grpc.unary_unary_rpc_method_handler(
          servicer.SetTransactionTableAvailable,
          request_deserializer=sql__floor__table__pb2.TransactionIdParam.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ft.FloorTableService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
