# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_types_pb2 as common__types__pb2
import sql_store_part_pb2 as sql__store__part__pb2


class storePartServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.reduceStorage = channel.unary_unary(
        '/sp.storePartService/reduceStorage',
        request_serializer=sql__store__part__pb2.transactionId.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.selectMenuItem = channel.unary_unary(
        '/sp.storePartService/selectMenuItem',
        request_serializer=sql__store__part__pb2.menuCardItemId.SerializeToString,
        response_deserializer=common__types__pb2.StoreItem.FromString,
        )
    self.getMenuItems = channel.unary_unary(
        '/sp.storePartService/getMenuItems',
        request_serializer=sql__store__part__pb2.menuCardId.SerializeToString,
        response_deserializer=sql__store__part__pb2.storeItemList.FromString,
        )
    self.insertSmurf = channel.unary_unary(
        '/sp.storePartService/insertSmurf',
        request_serializer=sql__store__part__pb2.newSmurfRequest.SerializeToString,
        response_deserializer=sql__store__part__pb2.storeSmurfId.FromString,
        )
    self.removeStorePart = channel.unary_unary(
        '/sp.storePartService/removeStorePart',
        request_serializer=sql__store__part__pb2.storePartId.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.calculateUsagePerYear = channel.unary_unary(
        '/sp.storePartService/calculateUsagePerYear',
        request_serializer=sql__store__part__pb2.itemId.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.calculateSoldOutDates = channel.unary_unary(
        '/sp.storePartService/calculateSoldOutDates',
        request_serializer=sql__store__part__pb2.itemId.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.calculateMenuTranslations = channel.unary_unary(
        '/sp.storePartService/calculateMenuTranslations',
        request_serializer=sql__store__part__pb2.itemId.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.calculateFirstDay = channel.unary_unary(
        '/sp.storePartService/calculateFirstDay',
        request_serializer=sql__store__part__pb2.itemId.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.calculateTotalSold = channel.unary_unary(
        '/sp.storePartService/calculateTotalSold',
        request_serializer=sql__store__part__pb2.itemId.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.updateSold = channel.unary_unary(
        '/sp.storePartService/updateSold',
        request_serializer=sql__store__part__pb2.itemId.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.getStorePartFromId = channel.unary_unary(
        '/sp.storePartService/getStorePartFromId',
        request_serializer=sql__store__part__pb2.storePartId.SerializeToString,
        response_deserializer=common__types__pb2.StorePart.FromString,
        )


class storePartServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def reduceStorage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def selectMenuItem(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getMenuItems(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def insertSmurf(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def removeStorePart(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def calculateUsagePerYear(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def calculateSoldOutDates(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def calculateMenuTranslations(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def calculateFirstDay(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def calculateTotalSold(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateSold(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getStorePartFromId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_storePartServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'reduceStorage': grpc.unary_unary_rpc_method_handler(
          servicer.reduceStorage,
          request_deserializer=sql__store__part__pb2.transactionId.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'selectMenuItem': grpc.unary_unary_rpc_method_handler(
          servicer.selectMenuItem,
          request_deserializer=sql__store__part__pb2.menuCardItemId.FromString,
          response_serializer=common__types__pb2.StoreItem.SerializeToString,
      ),
      'getMenuItems': grpc.unary_unary_rpc_method_handler(
          servicer.getMenuItems,
          request_deserializer=sql__store__part__pb2.menuCardId.FromString,
          response_serializer=sql__store__part__pb2.storeItemList.SerializeToString,
      ),
      'insertSmurf': grpc.unary_unary_rpc_method_handler(
          servicer.insertSmurf,
          request_deserializer=sql__store__part__pb2.newSmurfRequest.FromString,
          response_serializer=sql__store__part__pb2.storeSmurfId.SerializeToString,
      ),
      'removeStorePart': grpc.unary_unary_rpc_method_handler(
          servicer.removeStorePart,
          request_deserializer=sql__store__part__pb2.storePartId.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'calculateUsagePerYear': grpc.unary_unary_rpc_method_handler(
          servicer.calculateUsagePerYear,
          request_deserializer=sql__store__part__pb2.itemId.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'calculateSoldOutDates': grpc.unary_unary_rpc_method_handler(
          servicer.calculateSoldOutDates,
          request_deserializer=sql__store__part__pb2.itemId.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'calculateMenuTranslations': grpc.unary_unary_rpc_method_handler(
          servicer.calculateMenuTranslations,
          request_deserializer=sql__store__part__pb2.itemId.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'calculateFirstDay': grpc.unary_unary_rpc_method_handler(
          servicer.calculateFirstDay,
          request_deserializer=sql__store__part__pb2.itemId.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'calculateTotalSold': grpc.unary_unary_rpc_method_handler(
          servicer.calculateTotalSold,
          request_deserializer=sql__store__part__pb2.itemId.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'updateSold': grpc.unary_unary_rpc_method_handler(
          servicer.updateSold,
          request_deserializer=sql__store__part__pb2.itemId.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'getStorePartFromId': grpc.unary_unary_rpc_method_handler(
          servicer.getStorePartFromId,
          request_deserializer=sql__store__part__pb2.storePartId.FromString,
          response_serializer=common__types__pb2.StorePart.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sp.storePartService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
