# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sql_daily_transaction_print.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_types_pb2 as common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sql_daily_transaction_print.proto',
  package='dtp',
  syntax='proto3',
  serialized_pb=_b('\n!sql_daily_transaction_print.proto\x12\x03\x64tp\x1a\x12\x63ommon_types.proto\"J\n\x11SetPrintedRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\x12%\n\x06status\x18\x02 \x01(\x0e\x32\x15.common.PrinterStatus\"\x86\x02\n\tTimeFrame\x12\x13\n\x0b\x64\x61tabase_id\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\x16\n\x0etransaction_id\x18\x03 \x01(\x05\x12\x15\n\rtime_frame_id\x18\x04 \x01(\x05\x12\x11\n\tdevice_id\x18\x05 \x01(\x05\x12\x13\n\x0brfid_key_id\x18\x06 \x01(\x05\x12\x12\n\nprint_type\x18\x07 \x01(\x05\x12\x0f\n\x07printer\x18\x08 \x01(\x05\x12\x10\n\x08quantity\x18\t \x01(\x05\x12\x0f\n\x07tickets\x18\n \x01(\x05\x12\x10\n\x08priority\x18\x0b \x01(\x05\x12%\n\x06status\x18\x0c \x01(\x0e\x32\x15.common.PrinterStatus\"\xc1\x01\n\x15PrintTimeFrameRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\x12\x18\n\x10time_frame_index\x18\x02 \x01(\x05\x12\x11\n\tdevice_id\x18\x03 \x01(\x05\x12\x13\n\x0brfid_key_id\x18\x04 \x01(\x05\x12\x0e\n\x06prints\x18\x05 \x01(\x05\x12\x0f\n\x07tickets\x18\x06 \x01(\x05\x12\x17\n\x0f\x63ollect_printer\x18\x07 \x01(\x08\x12\x14\n\x0c\x62ill_printer\x18\x08 \x01(\x08\"\"\n\x0eVerifyResponse\x12\x10\n\x08verified\x18\x01 \x01(\x08\x32\xf3\x01\n\x1c\x44\x61ilyTransactionPrintService\x12\x33\n\x12\x46indPrintTimeFrame\x12\r.common.Empty\x1a\x0e.dtp.TimeFrame\x12;\n\x0ePrintTimeFrame\x12\x1a.dtp.PrintTimeFrameRequest\x1a\r.common.Empty\x12,\n\x06Verify\x12\r.common.Empty\x1a\x13.dtp.VerifyResponse\x12\x33\n\nSetPrinted\x12\x16.dtp.SetPrintedRequest\x1a\r.common.EmptyB%\n\x13\x63om.hha.daily.printP\x01\xaa\x02\x0bGrpcServiceb\x06proto3')
  ,
  dependencies=[common__types__pb2.DESCRIPTOR,])




_SETPRINTEDREQUEST = _descriptor.Descriptor(
  name='SetPrintedRequest',
  full_name='dtp.SetPrintedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='dtp.SetPrintedRequest.job_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='dtp.SetPrintedRequest.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=136,
)


_TIMEFRAME = _descriptor.Descriptor(
  name='TimeFrame',
  full_name='dtp.TimeFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database_id', full_name='dtp.TimeFrame.database_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='dtp.TimeFrame.time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transaction_id', full_name='dtp.TimeFrame.transaction_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_frame_id', full_name='dtp.TimeFrame.time_frame_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='dtp.TimeFrame.device_id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rfid_key_id', full_name='dtp.TimeFrame.rfid_key_id', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='print_type', full_name='dtp.TimeFrame.print_type', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='printer', full_name='dtp.TimeFrame.printer', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='dtp.TimeFrame.quantity', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tickets', full_name='dtp.TimeFrame.tickets', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priority', full_name='dtp.TimeFrame.priority', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='dtp.TimeFrame.status', index=11,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=401,
)


_PRINTTIMEFRAMEREQUEST = _descriptor.Descriptor(
  name='PrintTimeFrameRequest',
  full_name='dtp.PrintTimeFrameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction_id', full_name='dtp.PrintTimeFrameRequest.transaction_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_frame_index', full_name='dtp.PrintTimeFrameRequest.time_frame_index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='dtp.PrintTimeFrameRequest.device_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rfid_key_id', full_name='dtp.PrintTimeFrameRequest.rfid_key_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prints', full_name='dtp.PrintTimeFrameRequest.prints', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tickets', full_name='dtp.PrintTimeFrameRequest.tickets', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collect_printer', full_name='dtp.PrintTimeFrameRequest.collect_printer', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bill_printer', full_name='dtp.PrintTimeFrameRequest.bill_printer', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=597,
)


_VERIFYRESPONSE = _descriptor.Descriptor(
  name='VerifyResponse',
  full_name='dtp.VerifyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='verified', full_name='dtp.VerifyResponse.verified', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=599,
  serialized_end=633,
)

_SETPRINTEDREQUEST.fields_by_name['status'].enum_type = common__types__pb2._PRINTERSTATUS
_TIMEFRAME.fields_by_name['status'].enum_type = common__types__pb2._PRINTERSTATUS
DESCRIPTOR.message_types_by_name['SetPrintedRequest'] = _SETPRINTEDREQUEST
DESCRIPTOR.message_types_by_name['TimeFrame'] = _TIMEFRAME
DESCRIPTOR.message_types_by_name['PrintTimeFrameRequest'] = _PRINTTIMEFRAMEREQUEST
DESCRIPTOR.message_types_by_name['VerifyResponse'] = _VERIFYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetPrintedRequest = _reflection.GeneratedProtocolMessageType('SetPrintedRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETPRINTEDREQUEST,
  __module__ = 'sql_daily_transaction_print_pb2'
  # @@protoc_insertion_point(class_scope:dtp.SetPrintedRequest)
  ))
_sym_db.RegisterMessage(SetPrintedRequest)

TimeFrame = _reflection.GeneratedProtocolMessageType('TimeFrame', (_message.Message,), dict(
  DESCRIPTOR = _TIMEFRAME,
  __module__ = 'sql_daily_transaction_print_pb2'
  # @@protoc_insertion_point(class_scope:dtp.TimeFrame)
  ))
_sym_db.RegisterMessage(TimeFrame)

PrintTimeFrameRequest = _reflection.GeneratedProtocolMessageType('PrintTimeFrameRequest', (_message.Message,), dict(
  DESCRIPTOR = _PRINTTIMEFRAMEREQUEST,
  __module__ = 'sql_daily_transaction_print_pb2'
  # @@protoc_insertion_point(class_scope:dtp.PrintTimeFrameRequest)
  ))
_sym_db.RegisterMessage(PrintTimeFrameRequest)

VerifyResponse = _reflection.GeneratedProtocolMessageType('VerifyResponse', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYRESPONSE,
  __module__ = 'sql_daily_transaction_print_pb2'
  # @@protoc_insertion_point(class_scope:dtp.VerifyResponse)
  ))
_sym_db.RegisterMessage(VerifyResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\023com.hha.daily.printP\001\252\002\013GrpcService'))

_DAILYTRANSACTIONPRINTSERVICE = _descriptor.ServiceDescriptor(
  name='DailyTransactionPrintService',
  full_name='dtp.DailyTransactionPrintService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=636,
  serialized_end=879,
  methods=[
  _descriptor.MethodDescriptor(
    name='FindPrintTimeFrame',
    full_name='dtp.DailyTransactionPrintService.FindPrintTimeFrame',
    index=0,
    containing_service=None,
    input_type=common__types__pb2._EMPTY,
    output_type=_TIMEFRAME,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PrintTimeFrame',
    full_name='dtp.DailyTransactionPrintService.PrintTimeFrame',
    index=1,
    containing_service=None,
    input_type=_PRINTTIMEFRAMEREQUEST,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Verify',
    full_name='dtp.DailyTransactionPrintService.Verify',
    index=2,
    containing_service=None,
    input_type=common__types__pb2._EMPTY,
    output_type=_VERIFYRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetPrinted',
    full_name='dtp.DailyTransactionPrintService.SetPrinted',
    index=3,
    containing_service=None,
    input_type=_SETPRINTEDREQUEST,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DAILYTRANSACTIONPRINTSERVICE)

DESCRIPTOR.services_by_name['DailyTransactionPrintService'] = _DAILYTRANSACTIONPRINTSERVICE

# @@protoc_insertion_point(module_scope)
