# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sql_store_smurf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_types_pb2 as common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sql_store_smurf.proto',
  package='smurf',
  syntax='proto3',
  serialized_pb=_b('\n\x15sql_store_smurf.proto\x12\x05smurf\x1a\x12\x63ommon_types.proto\"L\n\x0fgetSmurfRequest\x12+\n\x0estore_smurf_id\x18\x01 \x01(\x0b\x32\x13.smurf.storeSmurfId\x12\x0c\n\x04name\x18\x02 \x01(\t\"&\n\x0cstoreSmurfId\x12\x16\n\x0estore_smurf_id\x18\x01 \x01(\x05\"3\n\x0estoreSmurfList\x12!\n\x05smurf\x18\x01 \x03(\x0b\x32\x12.common.StoreSmurf\"\x1a\n\nsearchName\x12\x0c\n\x04name\x18\x01 \x01(\t\"r\n\ntotalStore\x12\x10\n\x08prepared\x18\x02 \x01(\x05\x12\r\n\x05input\x18\x03 \x01(\x05\x12\x0f\n\x07ordered\x18\x04 \x01(\x05\x12\x11\n\tdelivered\x18\x05 \x01(\x05\x12\x0c\n\x04late\x18\x06 \x01(\x05\x12\x11\n\tcancelled\x18\x07 \x01(\x05\"F\n\x0ftotalStoreSmurf\x12\x10\n\x08smurf_id\x18\x01 \x01(\x05\x12!\n\x06totals\x18\x02 \x01(\x0b\x32\x11.smurf.totalStore\"3\n\rsmurfQuantity\x12\x10\n\x08smurf_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"0\n\ndangerName\x12\x14\n\x0c\x64\x61nger_level\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t2\xe4\x04\n\x11storeSmurfService\x12=\n\x0fsetSearchString\x12\x11.smurf.searchName\x1a\x15.smurf.storeSmurfList\"\x00\x12\x38\n\raddOrGetSmurf\x12\x11.smurf.dangerName\x1a\x12.common.StoreSmurf\"\x00\x12\x39\n\x0eupdateQuantity\x12\x16.smurf.totalStoreSmurf\x1a\r.common.Empty\"\x00\x12:\n\x12\x63\x61lculateTotalSold\x12\x13.smurf.storeSmurfId\x1a\r.common.Empty\"\x00\x12\x39\n\x11\x63\x61lculateFirstDay\x12\x13.smurf.storeSmurfId\x1a\r.common.Empty\"\x00\x12;\n\x13\x63\x61lculateTotalStock\x12\x13.smurf.storeSmurfId\x1a\r.common.Empty\"\x00\x12=\n\x15\x63\x61lculateUsagePerYear\x12\x13.smurf.storeSmurfId\x1a\r.common.Empty\"\x00\x12=\n\x15\x63\x61lculateSoldOutDates\x12\x13.smurf.storeSmurfId\x1a\r.common.Empty\"\x00\x12\x34\n\x0b\x61\x64\x64Quantity\x12\x14.smurf.smurfQuantity\x1a\r.common.Empty\"\x00\x12\x33\n\x0bremoveSmurf\x12\x13.smurf.storeSmurfId\x1a\r.common.Empty\"\x00\x42\x1f\n\x13\x63om.hha.store.smurfP\x01\xaa\x02\x05storeb\x06proto3')
  ,
  dependencies=[common__types__pb2.DESCRIPTOR,])




_GETSMURFREQUEST = _descriptor.Descriptor(
  name='getSmurfRequest',
  full_name='smurf.getSmurfRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='store_smurf_id', full_name='smurf.getSmurfRequest.store_smurf_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='smurf.getSmurfRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=128,
)


_STORESMURFID = _descriptor.Descriptor(
  name='storeSmurfId',
  full_name='smurf.storeSmurfId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='store_smurf_id', full_name='smurf.storeSmurfId.store_smurf_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=168,
)


_STORESMURFLIST = _descriptor.Descriptor(
  name='storeSmurfList',
  full_name='smurf.storeSmurfList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='smurf', full_name='smurf.storeSmurfList.smurf', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=221,
)


_SEARCHNAME = _descriptor.Descriptor(
  name='searchName',
  full_name='smurf.searchName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='smurf.searchName.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=249,
)


_TOTALSTORE = _descriptor.Descriptor(
  name='totalStore',
  full_name='smurf.totalStore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prepared', full_name='smurf.totalStore.prepared', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input', full_name='smurf.totalStore.input', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ordered', full_name='smurf.totalStore.ordered', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delivered', full_name='smurf.totalStore.delivered', index=3,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='late', full_name='smurf.totalStore.late', index=4,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cancelled', full_name='smurf.totalStore.cancelled', index=5,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=365,
)


_TOTALSTORESMURF = _descriptor.Descriptor(
  name='totalStoreSmurf',
  full_name='smurf.totalStoreSmurf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='smurf_id', full_name='smurf.totalStoreSmurf.smurf_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totals', full_name='smurf.totalStoreSmurf.totals', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=437,
)


_SMURFQUANTITY = _descriptor.Descriptor(
  name='smurfQuantity',
  full_name='smurf.smurfQuantity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='smurf_id', full_name='smurf.smurfQuantity.smurf_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='smurf.smurfQuantity.quantity', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=490,
)


_DANGERNAME = _descriptor.Descriptor(
  name='dangerName',
  full_name='smurf.dangerName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='danger_level', full_name='smurf.dangerName.danger_level', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='smurf.dangerName.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=540,
)

_GETSMURFREQUEST.fields_by_name['store_smurf_id'].message_type = _STORESMURFID
_STORESMURFLIST.fields_by_name['smurf'].message_type = common__types__pb2._STORESMURF
_TOTALSTORESMURF.fields_by_name['totals'].message_type = _TOTALSTORE
DESCRIPTOR.message_types_by_name['getSmurfRequest'] = _GETSMURFREQUEST
DESCRIPTOR.message_types_by_name['storeSmurfId'] = _STORESMURFID
DESCRIPTOR.message_types_by_name['storeSmurfList'] = _STORESMURFLIST
DESCRIPTOR.message_types_by_name['searchName'] = _SEARCHNAME
DESCRIPTOR.message_types_by_name['totalStore'] = _TOTALSTORE
DESCRIPTOR.message_types_by_name['totalStoreSmurf'] = _TOTALSTORESMURF
DESCRIPTOR.message_types_by_name['smurfQuantity'] = _SMURFQUANTITY
DESCRIPTOR.message_types_by_name['dangerName'] = _DANGERNAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

getSmurfRequest = _reflection.GeneratedProtocolMessageType('getSmurfRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETSMURFREQUEST,
  __module__ = 'sql_store_smurf_pb2'
  # @@protoc_insertion_point(class_scope:smurf.getSmurfRequest)
  ))
_sym_db.RegisterMessage(getSmurfRequest)

storeSmurfId = _reflection.GeneratedProtocolMessageType('storeSmurfId', (_message.Message,), dict(
  DESCRIPTOR = _STORESMURFID,
  __module__ = 'sql_store_smurf_pb2'
  # @@protoc_insertion_point(class_scope:smurf.storeSmurfId)
  ))
_sym_db.RegisterMessage(storeSmurfId)

storeSmurfList = _reflection.GeneratedProtocolMessageType('storeSmurfList', (_message.Message,), dict(
  DESCRIPTOR = _STORESMURFLIST,
  __module__ = 'sql_store_smurf_pb2'
  # @@protoc_insertion_point(class_scope:smurf.storeSmurfList)
  ))
_sym_db.RegisterMessage(storeSmurfList)

searchName = _reflection.GeneratedProtocolMessageType('searchName', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHNAME,
  __module__ = 'sql_store_smurf_pb2'
  # @@protoc_insertion_point(class_scope:smurf.searchName)
  ))
_sym_db.RegisterMessage(searchName)

totalStore = _reflection.GeneratedProtocolMessageType('totalStore', (_message.Message,), dict(
  DESCRIPTOR = _TOTALSTORE,
  __module__ = 'sql_store_smurf_pb2'
  # @@protoc_insertion_point(class_scope:smurf.totalStore)
  ))
_sym_db.RegisterMessage(totalStore)

totalStoreSmurf = _reflection.GeneratedProtocolMessageType('totalStoreSmurf', (_message.Message,), dict(
  DESCRIPTOR = _TOTALSTORESMURF,
  __module__ = 'sql_store_smurf_pb2'
  # @@protoc_insertion_point(class_scope:smurf.totalStoreSmurf)
  ))
_sym_db.RegisterMessage(totalStoreSmurf)

smurfQuantity = _reflection.GeneratedProtocolMessageType('smurfQuantity', (_message.Message,), dict(
  DESCRIPTOR = _SMURFQUANTITY,
  __module__ = 'sql_store_smurf_pb2'
  # @@protoc_insertion_point(class_scope:smurf.smurfQuantity)
  ))
_sym_db.RegisterMessage(smurfQuantity)

dangerName = _reflection.GeneratedProtocolMessageType('dangerName', (_message.Message,), dict(
  DESCRIPTOR = _DANGERNAME,
  __module__ = 'sql_store_smurf_pb2'
  # @@protoc_insertion_point(class_scope:smurf.dangerName)
  ))
_sym_db.RegisterMessage(dangerName)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\023com.hha.store.smurfP\001\252\002\005store'))

_STORESMURFSERVICE = _descriptor.ServiceDescriptor(
  name='storeSmurfService',
  full_name='smurf.storeSmurfService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=543,
  serialized_end=1155,
  methods=[
  _descriptor.MethodDescriptor(
    name='setSearchString',
    full_name='smurf.storeSmurfService.setSearchString',
    index=0,
    containing_service=None,
    input_type=_SEARCHNAME,
    output_type=_STORESMURFLIST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='addOrGetSmurf',
    full_name='smurf.storeSmurfService.addOrGetSmurf',
    index=1,
    containing_service=None,
    input_type=_DANGERNAME,
    output_type=common__types__pb2._STORESMURF,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='updateQuantity',
    full_name='smurf.storeSmurfService.updateQuantity',
    index=2,
    containing_service=None,
    input_type=_TOTALSTORESMURF,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='calculateTotalSold',
    full_name='smurf.storeSmurfService.calculateTotalSold',
    index=3,
    containing_service=None,
    input_type=_STORESMURFID,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='calculateFirstDay',
    full_name='smurf.storeSmurfService.calculateFirstDay',
    index=4,
    containing_service=None,
    input_type=_STORESMURFID,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='calculateTotalStock',
    full_name='smurf.storeSmurfService.calculateTotalStock',
    index=5,
    containing_service=None,
    input_type=_STORESMURFID,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='calculateUsagePerYear',
    full_name='smurf.storeSmurfService.calculateUsagePerYear',
    index=6,
    containing_service=None,
    input_type=_STORESMURFID,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='calculateSoldOutDates',
    full_name='smurf.storeSmurfService.calculateSoldOutDates',
    index=7,
    containing_service=None,
    input_type=_STORESMURFID,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='addQuantity',
    full_name='smurf.storeSmurfService.addQuantity',
    index=8,
    containing_service=None,
    input_type=_SMURFQUANTITY,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='removeSmurf',
    full_name='smurf.storeSmurfService.removeSmurf',
    index=9,
    containing_service=None,
    input_type=_STORESMURFID,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STORESMURFSERVICE)

DESCRIPTOR.services_by_name['storeSmurfService'] = _STORESMURFSERVICE

# @@protoc_insertion_point(module_scope)
