# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sql_supplier.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sql_supplier.proto',
  package='si',
  syntax='proto3',
  serialized_pb=_b('\n\x12sql_supplier.proto\x12\x02si\"\x1f\n\x0eGetNameRequest\x12\r\n\x05index\x18\x01 \x01(\x05\"\x1f\n\x0fGetNameResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\"&\n\x16SetSearchStringRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\")\n\x17SetSearchStringResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1f\n\x12GetSupplierRequest\x12\t\n\x01n\x18\x01 \x01(\x05\"H\n\x13GetSupplierResponse\x12\x13\n\x0bsupplier_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\x08\"-\n\x17\x41\x64\x64OrGetSupplierRequest\x12\x12\n\nlocal_name\x18\x02 \x01(\t\"*\n\x18\x41\x64\x64OrGetSupplierResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"I\n\x08Supplier\x12\x13\n\x0bsupplier_id\x18\x01 \x01(\x05\x12\x12\n\nlocal_name\x18\x02 \x01(\t\x12\x14\n\x0c\x63hinese_name\x18\x03 \x01(\t\".\n\x0cSupplierList\x12\x1e\n\x08supplier\x18\x01 \x03(\x0b\x32\x0c.si.Supplier2\xa1\x01\n\x0fSupplierService\x12?\n\x0fSetSearchString\x12\x1a.si.SetSearchStringRequest\x1a\x10.si.SupplierList\x12M\n\x10\x41\x64\x64OrGetSupplier\x12\x1b.si.AddOrGetSupplierRequest\x1a\x1c.si.AddOrGetSupplierResponseB\x1a\n\x16\x63om.hha.store.supplierP\x01\x62\x06proto3')
)




_GETNAMEREQUEST = _descriptor.Descriptor(
  name='GetNameRequest',
  full_name='si.GetNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='si.GetNameRequest.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=57,
)


_GETNAMERESPONSE = _descriptor.Descriptor(
  name='GetNameResponse',
  full_name='si.GetNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='si.GetNameResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=90,
)


_SETSEARCHSTRINGREQUEST = _descriptor.Descriptor(
  name='SetSearchStringRequest',
  full_name='si.SetSearchStringRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='si.SetSearchStringRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=130,
)


_SETSEARCHSTRINGRESPONSE = _descriptor.Descriptor(
  name='SetSearchStringResponse',
  full_name='si.SetSearchStringResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='si.SetSearchStringResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=173,
)


_GETSUPPLIERREQUEST = _descriptor.Descriptor(
  name='GetSupplierRequest',
  full_name='si.GetSupplierRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='si.GetSupplierRequest.n', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=206,
)


_GETSUPPLIERRESPONSE = _descriptor.Descriptor(
  name='GetSupplierResponse',
  full_name='si.GetSupplierResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='supplier_id', full_name='si.GetSupplierResponse.supplier_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='si.GetSupplierResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='si.GetSupplierResponse.result', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=280,
)


_ADDORGETSUPPLIERREQUEST = _descriptor.Descriptor(
  name='AddOrGetSupplierRequest',
  full_name='si.AddOrGetSupplierRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='local_name', full_name='si.AddOrGetSupplierRequest.local_name', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=327,
)


_ADDORGETSUPPLIERRESPONSE = _descriptor.Descriptor(
  name='AddOrGetSupplierResponse',
  full_name='si.AddOrGetSupplierResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='si.AddOrGetSupplierResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=371,
)


_SUPPLIER = _descriptor.Descriptor(
  name='Supplier',
  full_name='si.Supplier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='supplier_id', full_name='si.Supplier.supplier_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='local_name', full_name='si.Supplier.local_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chinese_name', full_name='si.Supplier.chinese_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=446,
)


_SUPPLIERLIST = _descriptor.Descriptor(
  name='SupplierList',
  full_name='si.SupplierList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='supplier', full_name='si.SupplierList.supplier', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=494,
)

_SUPPLIERLIST.fields_by_name['supplier'].message_type = _SUPPLIER
DESCRIPTOR.message_types_by_name['GetNameRequest'] = _GETNAMEREQUEST
DESCRIPTOR.message_types_by_name['GetNameResponse'] = _GETNAMERESPONSE
DESCRIPTOR.message_types_by_name['SetSearchStringRequest'] = _SETSEARCHSTRINGREQUEST
DESCRIPTOR.message_types_by_name['SetSearchStringResponse'] = _SETSEARCHSTRINGRESPONSE
DESCRIPTOR.message_types_by_name['GetSupplierRequest'] = _GETSUPPLIERREQUEST
DESCRIPTOR.message_types_by_name['GetSupplierResponse'] = _GETSUPPLIERRESPONSE
DESCRIPTOR.message_types_by_name['AddOrGetSupplierRequest'] = _ADDORGETSUPPLIERREQUEST
DESCRIPTOR.message_types_by_name['AddOrGetSupplierResponse'] = _ADDORGETSUPPLIERRESPONSE
DESCRIPTOR.message_types_by_name['Supplier'] = _SUPPLIER
DESCRIPTOR.message_types_by_name['SupplierList'] = _SUPPLIERLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetNameRequest = _reflection.GeneratedProtocolMessageType('GetNameRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETNAMEREQUEST,
  __module__ = 'sql_supplier_pb2'
  # @@protoc_insertion_point(class_scope:si.GetNameRequest)
  ))
_sym_db.RegisterMessage(GetNameRequest)

GetNameResponse = _reflection.GeneratedProtocolMessageType('GetNameResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETNAMERESPONSE,
  __module__ = 'sql_supplier_pb2'
  # @@protoc_insertion_point(class_scope:si.GetNameResponse)
  ))
_sym_db.RegisterMessage(GetNameResponse)

SetSearchStringRequest = _reflection.GeneratedProtocolMessageType('SetSearchStringRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETSEARCHSTRINGREQUEST,
  __module__ = 'sql_supplier_pb2'
  # @@protoc_insertion_point(class_scope:si.SetSearchStringRequest)
  ))
_sym_db.RegisterMessage(SetSearchStringRequest)

SetSearchStringResponse = _reflection.GeneratedProtocolMessageType('SetSearchStringResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETSEARCHSTRINGRESPONSE,
  __module__ = 'sql_supplier_pb2'
  # @@protoc_insertion_point(class_scope:si.SetSearchStringResponse)
  ))
_sym_db.RegisterMessage(SetSearchStringResponse)

GetSupplierRequest = _reflection.GeneratedProtocolMessageType('GetSupplierRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETSUPPLIERREQUEST,
  __module__ = 'sql_supplier_pb2'
  # @@protoc_insertion_point(class_scope:si.GetSupplierRequest)
  ))
_sym_db.RegisterMessage(GetSupplierRequest)

GetSupplierResponse = _reflection.GeneratedProtocolMessageType('GetSupplierResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETSUPPLIERRESPONSE,
  __module__ = 'sql_supplier_pb2'
  # @@protoc_insertion_point(class_scope:si.GetSupplierResponse)
  ))
_sym_db.RegisterMessage(GetSupplierResponse)

AddOrGetSupplierRequest = _reflection.GeneratedProtocolMessageType('AddOrGetSupplierRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDORGETSUPPLIERREQUEST,
  __module__ = 'sql_supplier_pb2'
  # @@protoc_insertion_point(class_scope:si.AddOrGetSupplierRequest)
  ))
_sym_db.RegisterMessage(AddOrGetSupplierRequest)

AddOrGetSupplierResponse = _reflection.GeneratedProtocolMessageType('AddOrGetSupplierResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDORGETSUPPLIERRESPONSE,
  __module__ = 'sql_supplier_pb2'
  # @@protoc_insertion_point(class_scope:si.AddOrGetSupplierResponse)
  ))
_sym_db.RegisterMessage(AddOrGetSupplierResponse)

Supplier = _reflection.GeneratedProtocolMessageType('Supplier', (_message.Message,), dict(
  DESCRIPTOR = _SUPPLIER,
  __module__ = 'sql_supplier_pb2'
  # @@protoc_insertion_point(class_scope:si.Supplier)
  ))
_sym_db.RegisterMessage(Supplier)

SupplierList = _reflection.GeneratedProtocolMessageType('SupplierList', (_message.Message,), dict(
  DESCRIPTOR = _SUPPLIERLIST,
  __module__ = 'sql_supplier_pb2'
  # @@protoc_insertion_point(class_scope:si.SupplierList)
  ))
_sym_db.RegisterMessage(SupplierList)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026com.hha.store.supplierP\001'))

_SUPPLIERSERVICE = _descriptor.ServiceDescriptor(
  name='SupplierService',
  full_name='si.SupplierService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=497,
  serialized_end=658,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetSearchString',
    full_name='si.SupplierService.SetSearchString',
    index=0,
    containing_service=None,
    input_type=_SETSEARCHSTRINGREQUEST,
    output_type=_SUPPLIERLIST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddOrGetSupplier',
    full_name='si.SupplierService.AddOrGetSupplier',
    index=1,
    containing_service=None,
    input_type=_ADDORGETSUPPLIERREQUEST,
    output_type=_ADDORGETSUPPLIERRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUPPLIERSERVICE)

DESCRIPTOR.services_by_name['SupplierService'] = _SUPPLIERSERVICE

# @@protoc_insertion_point(module_scope)
