# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_types_pb2 as common__types__pb2
import sql_archive_transaction_checksum_pb2 as sql__archive__transaction__checksum__pb2


class ArchiveTransactionChecksumServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Checksum = channel.unary_unary(
        '/atc.ArchiveTransactionChecksumService/Checksum',
        request_serializer=sql__archive__transaction__checksum__pb2.ChecksumRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.CopyChecksum = channel.unary_unary(
        '/atc.ArchiveTransactionChecksumService/CopyChecksum',
        request_serializer=sql__archive__transaction__checksum__pb2.CopyChecksumRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )


class ArchiveTransactionChecksumServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Checksum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CopyChecksum(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ArchiveTransactionChecksumServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Checksum': grpc.unary_unary_rpc_method_handler(
          servicer.Checksum,
          request_deserializer=sql__archive__transaction__checksum__pb2.ChecksumRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'CopyChecksum': grpc.unary_unary_rpc_method_handler(
          servicer.CopyChecksum,
          request_deserializer=sql__archive__transaction__checksum__pb2.CopyChecksumRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'atc.ArchiveTransactionChecksumService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
