# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sql_archive_transaction_checksum.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_types_pb2 as common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sql_archive_transaction_checksum.proto',
  package='atc',
  syntax='proto3',
  serialized_pb=_b('\n&sql_archive_transaction_checksum.proto\x12\x03\x61tc\x1a\x12\x63ommon_types.proto\"<\n\x13\x43opyChecksumRequest\x12\r\n\x05table\x18\x01 \x01(\t\x12\x16\n\x0etransaction_id\x18\x02 \x01(\x05\")\n\x0f\x43hecksumRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\x32\x91\x01\n!ArchiveTransactionChecksumService\x12\x31\n\x08\x43hecksum\x12\x14.atc.ChecksumRequest\x1a\r.common.Empty\"\x00\x12\x39\n\x0c\x43opyChecksum\x12\x18.atc.CopyChecksumRequest\x1a\r.common.Empty\"\x00\x42*\n\x18\x63om.hha.archive.checksumP\x01\xaa\x02\x0bGrpcServiceb\x06proto3')
  ,
  dependencies=[common__types__pb2.DESCRIPTOR,])




_COPYCHECKSUMREQUEST = _descriptor.Descriptor(
  name='CopyChecksumRequest',
  full_name='atc.CopyChecksumRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='atc.CopyChecksumRequest.table', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transaction_id', full_name='atc.CopyChecksumRequest.transaction_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=127,
)


_CHECKSUMREQUEST = _descriptor.Descriptor(
  name='ChecksumRequest',
  full_name='atc.ChecksumRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction_id', full_name='atc.ChecksumRequest.transaction_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=170,
)

DESCRIPTOR.message_types_by_name['CopyChecksumRequest'] = _COPYCHECKSUMREQUEST
DESCRIPTOR.message_types_by_name['ChecksumRequest'] = _CHECKSUMREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CopyChecksumRequest = _reflection.GeneratedProtocolMessageType('CopyChecksumRequest', (_message.Message,), dict(
  DESCRIPTOR = _COPYCHECKSUMREQUEST,
  __module__ = 'sql_archive_transaction_checksum_pb2'
  # @@protoc_insertion_point(class_scope:atc.CopyChecksumRequest)
  ))
_sym_db.RegisterMessage(CopyChecksumRequest)

ChecksumRequest = _reflection.GeneratedProtocolMessageType('ChecksumRequest', (_message.Message,), dict(
  DESCRIPTOR = _CHECKSUMREQUEST,
  __module__ = 'sql_archive_transaction_checksum_pb2'
  # @@protoc_insertion_point(class_scope:atc.ChecksumRequest)
  ))
_sym_db.RegisterMessage(ChecksumRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.hha.archive.checksumP\001\252\002\013GrpcService'))

_ARCHIVETRANSACTIONCHECKSUMSERVICE = _descriptor.ServiceDescriptor(
  name='ArchiveTransactionChecksumService',
  full_name='atc.ArchiveTransactionChecksumService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=173,
  serialized_end=318,
  methods=[
  _descriptor.MethodDescriptor(
    name='Checksum',
    full_name='atc.ArchiveTransactionChecksumService.Checksum',
    index=0,
    containing_service=None,
    input_type=_CHECKSUMREQUEST,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CopyChecksum',
    full_name='atc.ArchiveTransactionChecksumService.CopyChecksum',
    index=1,
    containing_service=None,
    input_type=_COPYCHECKSUMREQUEST,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARCHIVETRANSACTIONCHECKSUMSERVICE)

DESCRIPTOR.services_by_name['ArchiveTransactionChecksumService'] = _ARCHIVETRANSACTIONCHECKSUMSERVICE

# @@protoc_insertion_point(module_scope)
