# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sql_tax.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_types_pb2 as common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sql_tax.proto',
  package='tax',
  syntax='proto3',
  serialized_pb=_b('\n\rsql_tax.proto\x12\x03tax\x1a\x12\x63ommon_types.proto\"G\n\x0eSetRateRequest\x12!\n\x08tax_type\x18\x01 \x01(\x0e\x32\x0f.common.TaxType\x12\x12\n\npercentage\x18\x02 \x01(\x01\"!\n\x0c\x44umpResponse\x12\x11\n\tfile_name\x18\x01 \x01(\t\"3\n\x0eGetNameRequest\x12!\n\x08tax_type\x18\x01 \x01(\x0e\x32\x0f.common.TaxType\"\x1f\n\x0fGetNameResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\x0eVerifyResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"3\n\x0eGetRateRequest\x12!\n\x08tax_type\x18\x01 \x01(\x0e\x32\x0f.common.TaxType\"%\n\x0fGetRateResponse\x12\x12\n\npercentage\x18\x01 \x01(\x01\x32\xff\x01\n\nTaxService\x12-\n\x07SetRate\x12\x13.tax.SetRateRequest\x1a\r.common.Empty\x12\x34\n\x07GetName\x12\x13.tax.GetNameRequest\x1a\x14.tax.GetNameResponse\x12,\n\x06Verify\x12\r.common.Empty\x1a\x13.tax.VerifyResponse\x12\x34\n\x07GetRate\x12\x13.tax.GetRateRequest\x1a\x14.tax.GetRateResponse\x12(\n\x04\x44ump\x12\r.common.Empty\x1a\x11.tax.DumpResponseB\x0f\n\x0b\x63om.hha.taxP\x01\x62\x06proto3')
  ,
  dependencies=[common__types__pb2.DESCRIPTOR,])




_SETRATEREQUEST = _descriptor.Descriptor(
  name='SetRateRequest',
  full_name='tax.SetRateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tax_type', full_name='tax.SetRateRequest.tax_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='percentage', full_name='tax.SetRateRequest.percentage', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=113,
)


_DUMPRESPONSE = _descriptor.Descriptor(
  name='DumpResponse',
  full_name='tax.DumpResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='tax.DumpResponse.file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=148,
)


_GETNAMEREQUEST = _descriptor.Descriptor(
  name='GetNameRequest',
  full_name='tax.GetNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tax_type', full_name='tax.GetNameRequest.tax_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=201,
)


_GETNAMERESPONSE = _descriptor.Descriptor(
  name='GetNameResponse',
  full_name='tax.GetNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tax.GetNameResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=234,
)


_VERIFYRESPONSE = _descriptor.Descriptor(
  name='VerifyResponse',
  full_name='tax.VerifyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='tax.VerifyResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=268,
)


_GETRATEREQUEST = _descriptor.Descriptor(
  name='GetRateRequest',
  full_name='tax.GetRateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tax_type', full_name='tax.GetRateRequest.tax_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=321,
)


_GETRATERESPONSE = _descriptor.Descriptor(
  name='GetRateResponse',
  full_name='tax.GetRateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='percentage', full_name='tax.GetRateResponse.percentage', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=360,
)

_SETRATEREQUEST.fields_by_name['tax_type'].enum_type = common__types__pb2._TAXTYPE
_GETNAMEREQUEST.fields_by_name['tax_type'].enum_type = common__types__pb2._TAXTYPE
_GETRATEREQUEST.fields_by_name['tax_type'].enum_type = common__types__pb2._TAXTYPE
DESCRIPTOR.message_types_by_name['SetRateRequest'] = _SETRATEREQUEST
DESCRIPTOR.message_types_by_name['DumpResponse'] = _DUMPRESPONSE
DESCRIPTOR.message_types_by_name['GetNameRequest'] = _GETNAMEREQUEST
DESCRIPTOR.message_types_by_name['GetNameResponse'] = _GETNAMERESPONSE
DESCRIPTOR.message_types_by_name['VerifyResponse'] = _VERIFYRESPONSE
DESCRIPTOR.message_types_by_name['GetRateRequest'] = _GETRATEREQUEST
DESCRIPTOR.message_types_by_name['GetRateResponse'] = _GETRATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetRateRequest = _reflection.GeneratedProtocolMessageType('SetRateRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETRATEREQUEST,
  __module__ = 'sql_tax_pb2'
  # @@protoc_insertion_point(class_scope:tax.SetRateRequest)
  ))
_sym_db.RegisterMessage(SetRateRequest)

DumpResponse = _reflection.GeneratedProtocolMessageType('DumpResponse', (_message.Message,), dict(
  DESCRIPTOR = _DUMPRESPONSE,
  __module__ = 'sql_tax_pb2'
  # @@protoc_insertion_point(class_scope:tax.DumpResponse)
  ))
_sym_db.RegisterMessage(DumpResponse)

GetNameRequest = _reflection.GeneratedProtocolMessageType('GetNameRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETNAMEREQUEST,
  __module__ = 'sql_tax_pb2'
  # @@protoc_insertion_point(class_scope:tax.GetNameRequest)
  ))
_sym_db.RegisterMessage(GetNameRequest)

GetNameResponse = _reflection.GeneratedProtocolMessageType('GetNameResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETNAMERESPONSE,
  __module__ = 'sql_tax_pb2'
  # @@protoc_insertion_point(class_scope:tax.GetNameResponse)
  ))
_sym_db.RegisterMessage(GetNameResponse)

VerifyResponse = _reflection.GeneratedProtocolMessageType('VerifyResponse', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYRESPONSE,
  __module__ = 'sql_tax_pb2'
  # @@protoc_insertion_point(class_scope:tax.VerifyResponse)
  ))
_sym_db.RegisterMessage(VerifyResponse)

GetRateRequest = _reflection.GeneratedProtocolMessageType('GetRateRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETRATEREQUEST,
  __module__ = 'sql_tax_pb2'
  # @@protoc_insertion_point(class_scope:tax.GetRateRequest)
  ))
_sym_db.RegisterMessage(GetRateRequest)

GetRateResponse = _reflection.GeneratedProtocolMessageType('GetRateResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETRATERESPONSE,
  __module__ = 'sql_tax_pb2'
  # @@protoc_insertion_point(class_scope:tax.GetRateResponse)
  ))
_sym_db.RegisterMessage(GetRateResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\013com.hha.taxP\001'))

_TAXSERVICE = _descriptor.ServiceDescriptor(
  name='TaxService',
  full_name='tax.TaxService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=363,
  serialized_end=618,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetRate',
    full_name='tax.TaxService.SetRate',
    index=0,
    containing_service=None,
    input_type=_SETRATEREQUEST,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetName',
    full_name='tax.TaxService.GetName',
    index=1,
    containing_service=None,
    input_type=_GETNAMEREQUEST,
    output_type=_GETNAMERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Verify',
    full_name='tax.TaxService.Verify',
    index=2,
    containing_service=None,
    input_type=common__types__pb2._EMPTY,
    output_type=_VERIFYRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetRate',
    full_name='tax.TaxService.GetRate',
    index=3,
    containing_service=None,
    input_type=_GETRATEREQUEST,
    output_type=_GETRATERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Dump',
    full_name='tax.TaxService.Dump',
    index=4,
    containing_service=None,
    input_type=common__types__pb2._EMPTY,
    output_type=_DUMPRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TAXSERVICE)

DESCRIPTOR.services_by_name['TaxService'] = _TAXSERVICE

# @@protoc_insertion_point(module_scope)
