# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_types_pb2 as common__types__pb2
import sql_archive_transaction_payment_pb2 as sql__archive__transaction__payment__pb2


class ArchiveTransactionPaymentServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddPayment = channel.unary_unary(
        '/atp.ArchiveTransactionPaymentService/AddPayment',
        request_serializer=sql__archive__transaction__payment__pb2.AddPaymentRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.GetPaymentMoney = channel.unary_unary(
        '/atp.ArchiveTransactionPaymentService/GetPaymentMoney',
        request_serializer=sql__archive__transaction__payment__pb2.GetPaymentMoneyRequest.SerializeToString,
        response_deserializer=sql__archive__transaction__payment__pb2.PaymentDetailsList.FromString,
        )
    self.GetTransactionPaymentsList = channel.unary_unary(
        '/atp.ArchiveTransactionPaymentService/GetTransactionPaymentsList',
        request_serializer=sql__archive__transaction__payment__pb2.TransactionPaymentRequest.SerializeToString,
        response_deserializer=sql__archive__transaction__payment__pb2.PaymentList.FromString,
        )
    self.SelectTransactionId = channel.unary_unary(
        '/atp.ArchiveTransactionPaymentService/SelectTransactionId',
        request_serializer=sql__archive__transaction__payment__pb2.TransactionId.SerializeToString,
        response_deserializer=sql__archive__transaction__payment__pb2.PaymentDetailsList.FromString,
        )
    self.UpdateTransactionPaymentMethod = channel.unary_unary(
        '/atp.ArchiveTransactionPaymentService/UpdateTransactionPaymentMethod',
        request_serializer=sql__archive__transaction__payment__pb2.TransactionIdMethod.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.UpdateTransactionIdTotal = channel.unary_unary(
        '/atp.ArchiveTransactionPaymentService/UpdateTransactionIdTotal',
        request_serializer=sql__archive__transaction__payment__pb2.TransactionIdTotal.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )


class ArchiveTransactionPaymentServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddPayment(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPaymentMoney(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTransactionPaymentsList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SelectTransactionId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateTransactionPaymentMethod(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateTransactionIdTotal(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ArchiveTransactionPaymentServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddPayment': grpc.unary_unary_rpc_method_handler(
          servicer.AddPayment,
          request_deserializer=sql__archive__transaction__payment__pb2.AddPaymentRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'GetPaymentMoney': grpc.unary_unary_rpc_method_handler(
          servicer.GetPaymentMoney,
          request_deserializer=sql__archive__transaction__payment__pb2.GetPaymentMoneyRequest.FromString,
          response_serializer=sql__archive__transaction__payment__pb2.PaymentDetailsList.SerializeToString,
      ),
      'GetTransactionPaymentsList': grpc.unary_unary_rpc_method_handler(
          servicer.GetTransactionPaymentsList,
          request_deserializer=sql__archive__transaction__payment__pb2.TransactionPaymentRequest.FromString,
          response_serializer=sql__archive__transaction__payment__pb2.PaymentList.SerializeToString,
      ),
      'SelectTransactionId': grpc.unary_unary_rpc_method_handler(
          servicer.SelectTransactionId,
          request_deserializer=sql__archive__transaction__payment__pb2.TransactionId.FromString,
          response_serializer=sql__archive__transaction__payment__pb2.PaymentDetailsList.SerializeToString,
      ),
      'UpdateTransactionPaymentMethod': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateTransactionPaymentMethod,
          request_deserializer=sql__archive__transaction__payment__pb2.TransactionIdMethod.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'UpdateTransactionIdTotal': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateTransactionIdTotal,
          request_deserializer=sql__archive__transaction__payment__pb2.TransactionIdTotal.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'atp.ArchiveTransactionPaymentService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
