# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_types_pb2 as common__types__pb2
import sql_special_prices_pb2 as sql__special__prices__pb2


class SpecialPricesServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BackupSpecialPrices = channel.unary_unary(
        '/spp.SpecialPricesService/BackupSpecialPrices',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.ExchangeSpecialPrices = channel.unary_unary(
        '/spp.SpecialPricesService/ExchangeSpecialPrices',
        request_serializer=sql__special__prices__pb2.ExchangePricesRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.RemoveMenuCard = channel.unary_unary(
        '/spp.SpecialPricesService/RemoveMenuCard',
        request_serializer=common__types__pb2.MenuCardId.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.RestoreSpecialPrices = channel.unary_unary(
        '/spp.SpecialPricesService/RestoreSpecialPrices',
        request_serializer=common__types__pb2.Empty.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.SaveAllSpecialPrices = channel.unary_unary(
        '/spp.SpecialPricesService/SaveAllSpecialPrices',
        request_serializer=sql__special__prices__pb2.SaveSpecialPricesRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.SpecialPricExists = channel.unary_unary(
        '/spp.SpecialPricesService/SpecialPricExists',
        request_serializer=sql__special__prices__pb2.SpecialPriceIndex.SerializeToString,
        response_deserializer=sql__special__prices__pb2.ExistsReply.FromString,
        )
    self.UpdateSpecialPrice = channel.unary_unary(
        '/spp.SpecialPricesService/UpdateSpecialPrice',
        request_serializer=sql__special__prices__pb2.SpecialPriceOption.SerializeToString,
        response_deserializer=sql__special__prices__pb2.UpdateReply.FromString,
        )
    self.DuplicateSpecialPrice = channel.unary_unary(
        '/spp.SpecialPricesService/DuplicateSpecialPrice',
        request_serializer=sql__special__prices__pb2.DuplicateSpecialPriceRequest.SerializeToString,
        response_deserializer=sql__special__prices__pb2.SpecialPriceId.FromString,
        )
    self.EraseSpecialPrice = channel.unary_unary(
        '/spp.SpecialPricesService/EraseSpecialPrice',
        request_serializer=sql__special__prices__pb2.SpecialPriceIndex.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.DuplicateMenuCard = channel.unary_unary(
        '/spp.SpecialPricesService/DuplicateMenuCard',
        request_serializer=sql__special__prices__pb2.DuplicateMenuCardRequest.SerializeToString,
        response_deserializer=common__types__pb2.Empty.FromString,
        )
    self.GetSize = channel.unary_unary(
        '/spp.SpecialPricesService/GetSize',
        request_serializer=common__types__pb2.MenuCardId.SerializeToString,
        response_deserializer=sql__special__prices__pb2.GetSizeResponse.FromString,
        )
    self.GetSpecialPriceName = channel.unary_unary(
        '/spp.SpecialPricesService/GetSpecialPriceName',
        request_serializer=sql__special__prices__pb2.SpecialPriceNameRequest.SerializeToString,
        response_deserializer=sql__special__prices__pb2.SpecialPriceName.FromString,
        )
    self.FindAllSpecialPrices = channel.unary_unary(
        '/spp.SpecialPricesService/FindAllSpecialPrices',
        request_serializer=common__types__pb2.MenuCardId.SerializeToString,
        response_deserializer=sql__special__prices__pb2.SpecialPriceOptionList.FromString,
        )


class SpecialPricesServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def BackupSpecialPrices(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExchangeSpecialPrices(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveMenuCard(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RestoreSpecialPrices(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveAllSpecialPrices(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SpecialPricExists(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateSpecialPrice(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DuplicateSpecialPrice(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EraseSpecialPrice(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DuplicateMenuCard(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSpecialPriceName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindAllSpecialPrices(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SpecialPricesServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BackupSpecialPrices': grpc.unary_unary_rpc_method_handler(
          servicer.BackupSpecialPrices,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'ExchangeSpecialPrices': grpc.unary_unary_rpc_method_handler(
          servicer.ExchangeSpecialPrices,
          request_deserializer=sql__special__prices__pb2.ExchangePricesRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'RemoveMenuCard': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveMenuCard,
          request_deserializer=common__types__pb2.MenuCardId.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'RestoreSpecialPrices': grpc.unary_unary_rpc_method_handler(
          servicer.RestoreSpecialPrices,
          request_deserializer=common__types__pb2.Empty.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'SaveAllSpecialPrices': grpc.unary_unary_rpc_method_handler(
          servicer.SaveAllSpecialPrices,
          request_deserializer=sql__special__prices__pb2.SaveSpecialPricesRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'SpecialPricExists': grpc.unary_unary_rpc_method_handler(
          servicer.SpecialPricExists,
          request_deserializer=sql__special__prices__pb2.SpecialPriceIndex.FromString,
          response_serializer=sql__special__prices__pb2.ExistsReply.SerializeToString,
      ),
      'UpdateSpecialPrice': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateSpecialPrice,
          request_deserializer=sql__special__prices__pb2.SpecialPriceOption.FromString,
          response_serializer=sql__special__prices__pb2.UpdateReply.SerializeToString,
      ),
      'DuplicateSpecialPrice': grpc.unary_unary_rpc_method_handler(
          servicer.DuplicateSpecialPrice,
          request_deserializer=sql__special__prices__pb2.DuplicateSpecialPriceRequest.FromString,
          response_serializer=sql__special__prices__pb2.SpecialPriceId.SerializeToString,
      ),
      'EraseSpecialPrice': grpc.unary_unary_rpc_method_handler(
          servicer.EraseSpecialPrice,
          request_deserializer=sql__special__prices__pb2.SpecialPriceIndex.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'DuplicateMenuCard': grpc.unary_unary_rpc_method_handler(
          servicer.DuplicateMenuCard,
          request_deserializer=sql__special__prices__pb2.DuplicateMenuCardRequest.FromString,
          response_serializer=common__types__pb2.Empty.SerializeToString,
      ),
      'GetSize': grpc.unary_unary_rpc_method_handler(
          servicer.GetSize,
          request_deserializer=common__types__pb2.MenuCardId.FromString,
          response_serializer=sql__special__prices__pb2.GetSizeResponse.SerializeToString,
      ),
      'GetSpecialPriceName': grpc.unary_unary_rpc_method_handler(
          servicer.GetSpecialPriceName,
          request_deserializer=sql__special__prices__pb2.SpecialPriceNameRequest.FromString,
          response_serializer=sql__special__prices__pb2.SpecialPriceName.SerializeToString,
      ),
      'FindAllSpecialPrices': grpc.unary_unary_rpc_method_handler(
          servicer.FindAllSpecialPrices,
          request_deserializer=common__types__pb2.MenuCardId.FromString,
          response_serializer=sql__special__prices__pb2.SpecialPriceOptionList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'spp.SpecialPricesService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
