# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sql_address.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_types_pb2 as common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sql_address.proto',
  package='adr',
  syntax='proto3',
  serialized_pb=_b('\n\x11sql_address.proto\x12\x03\x61\x64r\x1a\x12\x63ommon_types.proto\"?\n\x0b\x41\x64\x64ressLine\x12\x0f\n\x07line_id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x03 \x01(\x05\"1\n\x0f\x41\x64\x64ressLineList\x12\x1e\n\x04line\x18\x01 \x03(\x0b\x32\x10.adr.AddressLine\"(\n\x16SetAddressLineResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"!\n\x11MysqlDumpResponse\x12\x0c\n\x04\x64ump\x18\x01 \x01(\t2\xda\x02\n\x0e\x41\x64\x64ressService\x12\x41\n\x0eSetAddressLine\x12\x10.adr.AddressLine\x1a\x1b.adr.SetAddressLineResponse\"\x00\x12\x34\n\tMysqlDump\x12\r.common.Empty\x1a\x16.adr.MysqlDumpResponse\"\x00\x12\x34\n\x0bGetAllLines\x12\r.common.Empty\x1a\x14.adr.AddressLineList\"\x00\x12/\n\rBackupAddress\x12\r.common.Empty\x1a\r.common.Empty\"\x00\x12\x30\n\x0eRestoreAddress\x12\r.common.Empty\x1a\r.common.Empty\"\x00\x12\x36\n\x11RemoveAddressLine\x12\x10.adr.AddressLine\x1a\r.common.Empty\"\x00\x42\x13\n\x0f\x63om.hha.addressP\x01\x62\x06proto3')
  ,
  dependencies=[common__types__pb2.DESCRIPTOR,])




_ADDRESSLINE = _descriptor.Descriptor(
  name='AddressLine',
  full_name='adr.AddressLine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line_id', full_name='adr.AddressLine.line_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='adr.AddressLine.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='features', full_name='adr.AddressLine.features', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=109,
)


_ADDRESSLINELIST = _descriptor.Descriptor(
  name='AddressLineList',
  full_name='adr.AddressLineList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line', full_name='adr.AddressLineList.line', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=160,
)


_SETADDRESSLINERESPONSE = _descriptor.Descriptor(
  name='SetAddressLineResponse',
  full_name='adr.SetAddressLineResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='adr.SetAddressLineResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=202,
)


_MYSQLDUMPRESPONSE = _descriptor.Descriptor(
  name='MysqlDumpResponse',
  full_name='adr.MysqlDumpResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dump', full_name='adr.MysqlDumpResponse.dump', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=237,
)

_ADDRESSLINELIST.fields_by_name['line'].message_type = _ADDRESSLINE
DESCRIPTOR.message_types_by_name['AddressLine'] = _ADDRESSLINE
DESCRIPTOR.message_types_by_name['AddressLineList'] = _ADDRESSLINELIST
DESCRIPTOR.message_types_by_name['SetAddressLineResponse'] = _SETADDRESSLINERESPONSE
DESCRIPTOR.message_types_by_name['MysqlDumpResponse'] = _MYSQLDUMPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddressLine = _reflection.GeneratedProtocolMessageType('AddressLine', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESSLINE,
  __module__ = 'sql_address_pb2'
  # @@protoc_insertion_point(class_scope:adr.AddressLine)
  ))
_sym_db.RegisterMessage(AddressLine)

AddressLineList = _reflection.GeneratedProtocolMessageType('AddressLineList', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESSLINELIST,
  __module__ = 'sql_address_pb2'
  # @@protoc_insertion_point(class_scope:adr.AddressLineList)
  ))
_sym_db.RegisterMessage(AddressLineList)

SetAddressLineResponse = _reflection.GeneratedProtocolMessageType('SetAddressLineResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETADDRESSLINERESPONSE,
  __module__ = 'sql_address_pb2'
  # @@protoc_insertion_point(class_scope:adr.SetAddressLineResponse)
  ))
_sym_db.RegisterMessage(SetAddressLineResponse)

MysqlDumpResponse = _reflection.GeneratedProtocolMessageType('MysqlDumpResponse', (_message.Message,), dict(
  DESCRIPTOR = _MYSQLDUMPRESPONSE,
  __module__ = 'sql_address_pb2'
  # @@protoc_insertion_point(class_scope:adr.MysqlDumpResponse)
  ))
_sym_db.RegisterMessage(MysqlDumpResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\017com.hha.addressP\001'))

_ADDRESSSERVICE = _descriptor.ServiceDescriptor(
  name='AddressService',
  full_name='adr.AddressService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=240,
  serialized_end=586,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetAddressLine',
    full_name='adr.AddressService.SetAddressLine',
    index=0,
    containing_service=None,
    input_type=_ADDRESSLINE,
    output_type=_SETADDRESSLINERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MysqlDump',
    full_name='adr.AddressService.MysqlDump',
    index=1,
    containing_service=None,
    input_type=common__types__pb2._EMPTY,
    output_type=_MYSQLDUMPRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllLines',
    full_name='adr.AddressService.GetAllLines',
    index=2,
    containing_service=None,
    input_type=common__types__pb2._EMPTY,
    output_type=_ADDRESSLINELIST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='BackupAddress',
    full_name='adr.AddressService.BackupAddress',
    index=3,
    containing_service=None,
    input_type=common__types__pb2._EMPTY,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RestoreAddress',
    full_name='adr.AddressService.RestoreAddress',
    index=4,
    containing_service=None,
    input_type=common__types__pb2._EMPTY,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveAddressLine',
    full_name='adr.AddressService.RemoveAddressLine',
    index=5,
    containing_service=None,
    input_type=_ADDRESSLINE,
    output_type=common__types__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADDRESSSERVICE)

DESCRIPTOR.services_by_name['AddressService'] = _ADDRESSSERVICE

# @@protoc_insertion_point(module_scope)
